// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.12.4
// source: pkg/proto/mailer.proto

package mailer

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ShareReportEmail struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Link          string                 `protobuf:"bytes,2,opt,name=link,proto3" json:"link,omitempty"`
	Email         string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	AppointmentId uint32                 `protobuf:"varint,4,opt,name=appointmentId,proto3" json:"appointmentId,omitempty"`
	ReportId      uint32                 `protobuf:"varint,5,opt,name=reportId,proto3" json:"reportId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShareReportEmail) Reset() {
	*x = ShareReportEmail{}
	mi := &file_pkg_proto_mailer_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShareReportEmail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShareReportEmail) ProtoMessage() {}

func (x *ShareReportEmail) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_mailer_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShareReportEmail.ProtoReflect.Descriptor instead.
func (*ShareReportEmail) Descriptor() ([]byte, []int) {
	return file_pkg_proto_mailer_proto_rawDescGZIP(), []int{0}
}

func (x *ShareReportEmail) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ShareReportEmail) GetLink() string {
	if x != nil {
		return x.Link
	}
	return ""
}

func (x *ShareReportEmail) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *ShareReportEmail) GetAppointmentId() uint32 {
	if x != nil {
		return x.AppointmentId
	}
	return 0
}

func (x *ShareReportEmail) GetReportId() uint32 {
	if x != nil {
		return x.ReportId
	}
	return 0
}

type RequestResetDataEmail struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DoctorName    string                 `protobuf:"bytes,1,opt,name=doctorName,proto3" json:"doctorName,omitempty"`
	Code          string                 `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	Email         string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestResetDataEmail) Reset() {
	*x = RequestResetDataEmail{}
	mi := &file_pkg_proto_mailer_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestResetDataEmail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestResetDataEmail) ProtoMessage() {}

func (x *RequestResetDataEmail) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_mailer_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestResetDataEmail.ProtoReflect.Descriptor instead.
func (*RequestResetDataEmail) Descriptor() ([]byte, []int) {
	return file_pkg_proto_mailer_proto_rawDescGZIP(), []int{1}
}

func (x *RequestResetDataEmail) GetDoctorName() string {
	if x != nil {
		return x.DoctorName
	}
	return ""
}

func (x *RequestResetDataEmail) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *RequestResetDataEmail) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type WelcomeDoctorEmail struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DoctorName    string                 `protobuf:"bytes,1,opt,name=doctorName,proto3" json:"doctorName,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	Email         string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WelcomeDoctorEmail) Reset() {
	*x = WelcomeDoctorEmail{}
	mi := &file_pkg_proto_mailer_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WelcomeDoctorEmail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WelcomeDoctorEmail) ProtoMessage() {}

func (x *WelcomeDoctorEmail) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_mailer_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WelcomeDoctorEmail.ProtoReflect.Descriptor instead.
func (*WelcomeDoctorEmail) Descriptor() ([]byte, []int) {
	return file_pkg_proto_mailer_proto_rawDescGZIP(), []int{2}
}

func (x *WelcomeDoctorEmail) GetDoctorName() string {
	if x != nil {
		return x.DoctorName
	}
	return ""
}

func (x *WelcomeDoctorEmail) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *WelcomeDoctorEmail) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

var File_pkg_proto_mailer_proto protoreflect.FileDescriptor

const file_pkg_proto_mailer_proto_rawDesc = "" +
	"\n" +
	"\x16pkg/proto/mailer.proto\x12\x05proto\"\x92\x01\n" +
	"\x10ShareReportEmail\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04link\x18\x02 \x01(\tR\x04link\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x12$\n" +
	"\rappointmentId\x18\x04 \x01(\rR\rappointmentId\x12\x1a\n" +
	"\breportId\x18\x05 \x01(\rR\breportId\"a\n" +
	"\x15RequestResetDataEmail\x12\x1e\n" +
	"\n" +
	"doctorName\x18\x01 \x01(\tR\n" +
	"doctorName\x12\x12\n" +
	"\x04code\x18\x02 \x01(\tR\x04code\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\"f\n" +
	"\x12WelcomeDoctorEmail\x12\x1e\n" +
	"\n" +
	"doctorName\x18\x01 \x01(\tR\n" +
	"doctorName\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05emailB\x12Z\x10pkg/proto/mailerb\x06proto3"

var (
	file_pkg_proto_mailer_proto_rawDescOnce sync.Once
	file_pkg_proto_mailer_proto_rawDescData []byte
)

func file_pkg_proto_mailer_proto_rawDescGZIP() []byte {
	file_pkg_proto_mailer_proto_rawDescOnce.Do(func() {
		file_pkg_proto_mailer_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_proto_mailer_proto_rawDesc), len(file_pkg_proto_mailer_proto_rawDesc)))
	})
	return file_pkg_proto_mailer_proto_rawDescData
}

var file_pkg_proto_mailer_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_pkg_proto_mailer_proto_goTypes = []any{
	(*ShareReportEmail)(nil),      // 0: proto.ShareReportEmail
	(*RequestResetDataEmail)(nil), // 1: proto.RequestResetDataEmail
	(*WelcomeDoctorEmail)(nil),    // 2: proto.WelcomeDoctorEmail
}
var file_pkg_proto_mailer_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pkg_proto_mailer_proto_init() }
func file_pkg_proto_mailer_proto_init() {
	if File_pkg_proto_mailer_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_proto_mailer_proto_rawDesc), len(file_pkg_proto_mailer_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pkg_proto_mailer_proto_goTypes,
		DependencyIndexes: file_pkg_proto_mailer_proto_depIdxs,
		MessageInfos:      file_pkg_proto_mailer_proto_msgTypes,
	}.Build()
	File_pkg_proto_mailer_proto = out.File
	file_pkg_proto_mailer_proto_goTypes = nil
	file_pkg_proto_mailer_proto_depIdxs = nil
}
