// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.12.4
// source: referral.proto

package referral

import (
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ReferringCenter struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`                                     // Use uint32 for ID as Proto doesn't support uint
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`                                  // Required name
	PhoneNumber   string                 `protobuf:"bytes,3,opt,name=phone_number,json=phoneNumber,proto3" json:"phone_number,omitempty"` // Nullable phone number
	Address       string                 `protobuf:"bytes,4,opt,name=address,proto3" json:"address,omitempty"`                            // Nullable address
	IsDeleted     bool                   `protobuf:"varint,5,opt,name=is_deleted,json=isDeleted,proto3" json:"is_deleted,omitempty"`      // Default: false
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReferringCenter) Reset() {
	*x = ReferringCenter{}
	mi := &file_referral_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReferringCenter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReferringCenter) ProtoMessage() {}

func (x *ReferringCenter) ProtoReflect() protoreflect.Message {
	mi := &file_referral_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReferringCenter.ProtoReflect.Descriptor instead.
func (*ReferringCenter) Descriptor() ([]byte, []int) {
	return file_referral_proto_rawDescGZIP(), []int{0}
}

func (x *ReferringCenter) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ReferringCenter) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ReferringCenter) GetPhoneNumber() string {
	if x != nil {
		return x.PhoneNumber
	}
	return ""
}

func (x *ReferringCenter) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *ReferringCenter) GetIsDeleted() bool {
	if x != nil {
		return x.IsDeleted
	}
	return false
}

type ReferringDoctor struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Id                 uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`                                                             // Use uint32 for ID
	FirstName          string                 `protobuf:"bytes,2,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`                               // Required first name
	LastName           string                 `protobuf:"bytes,3,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`                                  // Required last name
	PhoneNumber        string                 `protobuf:"bytes,4,opt,name=phone_number,json=phoneNumber,proto3" json:"phone_number,omitempty"`                         // Required phone number
	Email              string                 `protobuf:"bytes,5,opt,name=email,proto3" json:"email,omitempty"`                                                        // Nullable email
	ReferringCenterId  uint32                 `protobuf:"varint,6,opt,name=referring_center_id,json=referringCenterId,proto3" json:"referring_center_id,omitempty"`    // Nullable ReferringCenter ID
	ReferringCenter    *ReferringCenter       `protobuf:"bytes,7,opt,name=referring_center,json=referringCenter,proto3" json:"referring_center,omitempty"`             // Optional referring center (nested message)
	DeviceId           string                 `protobuf:"bytes,8,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`                                  // Nullable device ID
	HasUpdatedPassword bool                   `protobuf:"varint,9,opt,name=has_updated_password,json=hasUpdatedPassword,proto3" json:"has_updated_password,omitempty"` // Default: false
	IsAccessRequest    bool                   `protobuf:"varint,10,opt,name=is_access_request,json=isAccessRequest,proto3" json:"is_access_request,omitempty"`         // Required flag
	IsDisabled         bool                   `protobuf:"varint,11,opt,name=is_disabled,json=isDisabled,proto3" json:"is_disabled,omitempty"`                          // Required flag
	IsDeleted          bool                   `protobuf:"varint,12,opt,name=is_deleted,json=isDeleted,proto3" json:"is_deleted,omitempty"`                             // Required flag
	LastLogin          *timestamp.Timestamp   `protobuf:"bytes,13,opt,name=last_login,json=lastLogin,proto3" json:"last_login,omitempty"`                              // Last login time
	CreatedAt          *timestamp.Timestamp   `protobuf:"bytes,14,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`                              // Created at time
	Password           string                 `protobuf:"bytes,15,opt,name=password,proto3" json:"password,omitempty"`
	Profession         string                 `protobuf:"bytes,16,opt,name=profession,proto3" json:"profession,omitempty"`
	LicenseNumber      string                 `protobuf:"bytes,17,opt,name=license_number,json=licenseNumber,proto3" json:"license_number,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ReferringDoctor) Reset() {
	*x = ReferringDoctor{}
	mi := &file_referral_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReferringDoctor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReferringDoctor) ProtoMessage() {}

func (x *ReferringDoctor) ProtoReflect() protoreflect.Message {
	mi := &file_referral_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReferringDoctor.ProtoReflect.Descriptor instead.
func (*ReferringDoctor) Descriptor() ([]byte, []int) {
	return file_referral_proto_rawDescGZIP(), []int{1}
}

func (x *ReferringDoctor) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ReferringDoctor) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *ReferringDoctor) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

func (x *ReferringDoctor) GetPhoneNumber() string {
	if x != nil {
		return x.PhoneNumber
	}
	return ""
}

func (x *ReferringDoctor) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *ReferringDoctor) GetReferringCenterId() uint32 {
	if x != nil {
		return x.ReferringCenterId
	}
	return 0
}

func (x *ReferringDoctor) GetReferringCenter() *ReferringCenter {
	if x != nil {
		return x.ReferringCenter
	}
	return nil
}

func (x *ReferringDoctor) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *ReferringDoctor) GetHasUpdatedPassword() bool {
	if x != nil {
		return x.HasUpdatedPassword
	}
	return false
}

func (x *ReferringDoctor) GetIsAccessRequest() bool {
	if x != nil {
		return x.IsAccessRequest
	}
	return false
}

func (x *ReferringDoctor) GetIsDisabled() bool {
	if x != nil {
		return x.IsDisabled
	}
	return false
}

func (x *ReferringDoctor) GetIsDeleted() bool {
	if x != nil {
		return x.IsDeleted
	}
	return false
}

func (x *ReferringDoctor) GetLastLogin() *timestamp.Timestamp {
	if x != nil {
		return x.LastLogin
	}
	return nil
}

func (x *ReferringDoctor) GetCreatedAt() *timestamp.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *ReferringDoctor) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *ReferringDoctor) GetProfession() string {
	if x != nil {
		return x.Profession
	}
	return ""
}

func (x *ReferringDoctor) GetLicenseNumber() string {
	if x != nil {
		return x.LicenseNumber
	}
	return ""
}

type DoctorLoggedIn struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DoctorId      uint32                 `protobuf:"varint,1,opt,name=doctorId,proto3" json:"doctorId,omitempty"`
	DeviceId      string                 `protobuf:"bytes,2,opt,name=deviceId,proto3" json:"deviceId,omitempty"`
	Time          *timestamp.Timestamp   `protobuf:"bytes,3,opt,name=time,proto3" json:"time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DoctorLoggedIn) Reset() {
	*x = DoctorLoggedIn{}
	mi := &file_referral_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DoctorLoggedIn) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DoctorLoggedIn) ProtoMessage() {}

func (x *DoctorLoggedIn) ProtoReflect() protoreflect.Message {
	mi := &file_referral_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DoctorLoggedIn.ProtoReflect.Descriptor instead.
func (*DoctorLoggedIn) Descriptor() ([]byte, []int) {
	return file_referral_proto_rawDescGZIP(), []int{2}
}

func (x *DoctorLoggedIn) GetDoctorId() uint32 {
	if x != nil {
		return x.DoctorId
	}
	return 0
}

func (x *DoctorLoggedIn) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *DoctorLoggedIn) GetTime() *timestamp.Timestamp {
	if x != nil {
		return x.Time
	}
	return nil
}

type DoctorWalletPayCommission struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DoctorId      uint32                 `protobuf:"varint,1,opt,name=doctorId,proto3" json:"doctorId,omitempty"`
	Commission    float64                `protobuf:"fixed64,2,opt,name=commission,proto3" json:"commission,omitempty"`
	AppointmentId uint32                 `protobuf:"varint,3,opt,name=appointmentId,proto3" json:"appointmentId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DoctorWalletPayCommission) Reset() {
	*x = DoctorWalletPayCommission{}
	mi := &file_referral_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DoctorWalletPayCommission) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DoctorWalletPayCommission) ProtoMessage() {}

func (x *DoctorWalletPayCommission) ProtoReflect() protoreflect.Message {
	mi := &file_referral_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DoctorWalletPayCommission.ProtoReflect.Descriptor instead.
func (*DoctorWalletPayCommission) Descriptor() ([]byte, []int) {
	return file_referral_proto_rawDescGZIP(), []int{3}
}

func (x *DoctorWalletPayCommission) GetDoctorId() uint32 {
	if x != nil {
		return x.DoctorId
	}
	return 0
}

func (x *DoctorWalletPayCommission) GetCommission() float64 {
	if x != nil {
		return x.Commission
	}
	return 0
}

func (x *DoctorWalletPayCommission) GetAppointmentId() uint32 {
	if x != nil {
		return x.AppointmentId
	}
	return 0
}

type TempAppointment struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Id                uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	FirstName         string                 `protobuf:"bytes,2,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName          string                 `protobuf:"bytes,3,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	PhoneNumber       string                 `protobuf:"bytes,4,opt,name=phone_number,json=phoneNumber,proto3" json:"phone_number,omitempty"`
	ExaminationDate   *timestamp.Timestamp   `protobuf:"bytes,5,opt,name=examination_date,json=examinationDate,proto3" json:"examination_date,omitempty"`
	Age               int32                  `protobuf:"varint,6,opt,name=age,proto3" json:"age,omitempty"`
	ProcedureId       uint32                 `protobuf:"varint,7,opt,name=procedure_id,json=procedureId,proto3" json:"procedure_id,omitempty"`
	OtherProcedure    string                 `protobuf:"bytes,9,opt,name=other_procedure,json=otherProcedure,proto3" json:"other_procedure,omitempty"`
	ModalityId        uint32                 `protobuf:"varint,10,opt,name=modality_id,json=modalityId,proto3" json:"modality_id,omitempty"`
	ReferringDoctorId uint32                 `protobuf:"varint,12,opt,name=referring_doctor_id,json=referringDoctorId,proto3" json:"referring_doctor_id,omitempty"`
	ClinicalHistory   string                 `protobuf:"bytes,14,opt,name=clinical_history,json=clinicalHistory,proto3" json:"clinical_history,omitempty"`
	ReferringCenter   string                 `protobuf:"bytes,15,opt,name=referring_center,json=referringCenter,proto3" json:"referring_center,omitempty"`
	Sex               string                 `protobuf:"bytes,16,opt,name=sex,proto3" json:"sex,omitempty"`
	Address           string                 `protobuf:"bytes,17,opt,name=address,proto3" json:"address,omitempty"`
	RequestFormUrl    string                 `protobuf:"bytes,18,opt,name=request_form_url,json=requestFormUrl,proto3" json:"request_form_url,omitempty"`
	IsMoved           bool                   `protobuf:"varint,19,opt,name=is_moved,json=isMoved,proto3" json:"is_moved,omitempty"`
	IsDeleted         bool                   `protobuf:"varint,20,opt,name=is_deleted,json=isDeleted,proto3" json:"is_deleted,omitempty"`
	IsCompleted       bool                   `protobuf:"varint,21,opt,name=is_completed,json=isCompleted,proto3" json:"is_completed,omitempty"`
	CreatedAt         *timestamp.Timestamp   `protobuf:"bytes,22,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt         *timestamp.Timestamp   `protobuf:"bytes,23,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *TempAppointment) Reset() {
	*x = TempAppointment{}
	mi := &file_referral_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TempAppointment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TempAppointment) ProtoMessage() {}

func (x *TempAppointment) ProtoReflect() protoreflect.Message {
	mi := &file_referral_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TempAppointment.ProtoReflect.Descriptor instead.
func (*TempAppointment) Descriptor() ([]byte, []int) {
	return file_referral_proto_rawDescGZIP(), []int{4}
}

func (x *TempAppointment) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *TempAppointment) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *TempAppointment) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

func (x *TempAppointment) GetPhoneNumber() string {
	if x != nil {
		return x.PhoneNumber
	}
	return ""
}

func (x *TempAppointment) GetExaminationDate() *timestamp.Timestamp {
	if x != nil {
		return x.ExaminationDate
	}
	return nil
}

func (x *TempAppointment) GetAge() int32 {
	if x != nil {
		return x.Age
	}
	return 0
}

func (x *TempAppointment) GetProcedureId() uint32 {
	if x != nil {
		return x.ProcedureId
	}
	return 0
}

func (x *TempAppointment) GetOtherProcedure() string {
	if x != nil {
		return x.OtherProcedure
	}
	return ""
}

func (x *TempAppointment) GetModalityId() uint32 {
	if x != nil {
		return x.ModalityId
	}
	return 0
}

func (x *TempAppointment) GetReferringDoctorId() uint32 {
	if x != nil {
		return x.ReferringDoctorId
	}
	return 0
}

func (x *TempAppointment) GetClinicalHistory() string {
	if x != nil {
		return x.ClinicalHistory
	}
	return ""
}

func (x *TempAppointment) GetReferringCenter() string {
	if x != nil {
		return x.ReferringCenter
	}
	return ""
}

func (x *TempAppointment) GetSex() string {
	if x != nil {
		return x.Sex
	}
	return ""
}

func (x *TempAppointment) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *TempAppointment) GetRequestFormUrl() string {
	if x != nil {
		return x.RequestFormUrl
	}
	return ""
}

func (x *TempAppointment) GetIsMoved() bool {
	if x != nil {
		return x.IsMoved
	}
	return false
}

func (x *TempAppointment) GetIsDeleted() bool {
	if x != nil {
		return x.IsDeleted
	}
	return false
}

func (x *TempAppointment) GetIsCompleted() bool {
	if x != nil {
		return x.IsCompleted
	}
	return false
}

func (x *TempAppointment) GetCreatedAt() *timestamp.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *TempAppointment) GetUpdatedAt() *timestamp.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

var File_referral_proto protoreflect.FileDescriptor

const file_referral_proto_rawDesc = "" +
	"\n" +
	"\x0ereferral.proto\x12\x05proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\x91\x01\n" +
	"\x0fReferringCenter\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12!\n" +
	"\fphone_number\x18\x03 \x01(\tR\vphoneNumber\x12\x18\n" +
	"\aaddress\x18\x04 \x01(\tR\aaddress\x12\x1d\n" +
	"\n" +
	"is_deleted\x18\x05 \x01(\bR\tisDeleted\"\x9d\x05\n" +
	"\x0fReferringDoctor\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x1d\n" +
	"\n" +
	"first_name\x18\x02 \x01(\tR\tfirstName\x12\x1b\n" +
	"\tlast_name\x18\x03 \x01(\tR\blastName\x12!\n" +
	"\fphone_number\x18\x04 \x01(\tR\vphoneNumber\x12\x14\n" +
	"\x05email\x18\x05 \x01(\tR\x05email\x12.\n" +
	"\x13referring_center_id\x18\x06 \x01(\rR\x11referringCenterId\x12A\n" +
	"\x10referring_center\x18\a \x01(\v2\x16.proto.ReferringCenterR\x0freferringCenter\x12\x1b\n" +
	"\tdevice_id\x18\b \x01(\tR\bdeviceId\x120\n" +
	"\x14has_updated_password\x18\t \x01(\bR\x12hasUpdatedPassword\x12*\n" +
	"\x11is_access_request\x18\n" +
	" \x01(\bR\x0fisAccessRequest\x12\x1f\n" +
	"\vis_disabled\x18\v \x01(\bR\n" +
	"isDisabled\x12\x1d\n" +
	"\n" +
	"is_deleted\x18\f \x01(\bR\tisDeleted\x129\n" +
	"\n" +
	"last_login\x18\r \x01(\v2\x1a.google.protobuf.TimestampR\tlastLogin\x129\n" +
	"\n" +
	"created_at\x18\x0e \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12\x1a\n" +
	"\bpassword\x18\x0f \x01(\tR\bpassword\x12\x1e\n" +
	"\n" +
	"profession\x18\x10 \x01(\tR\n" +
	"profession\x12%\n" +
	"\x0elicense_number\x18\x11 \x01(\tR\rlicenseNumber\"x\n" +
	"\x0eDoctorLoggedIn\x12\x1a\n" +
	"\bdoctorId\x18\x01 \x01(\rR\bdoctorId\x12\x1a\n" +
	"\bdeviceId\x18\x02 \x01(\tR\bdeviceId\x12.\n" +
	"\x04time\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\x04time\"}\n" +
	"\x19DoctorWalletPayCommission\x12\x1a\n" +
	"\bdoctorId\x18\x01 \x01(\rR\bdoctorId\x12\x1e\n" +
	"\n" +
	"commission\x18\x02 \x01(\x01R\n" +
	"commission\x12$\n" +
	"\rappointmentId\x18\x03 \x01(\rR\rappointmentId\"\xf5\x05\n" +
	"\x0fTempAppointment\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x1d\n" +
	"\n" +
	"first_name\x18\x02 \x01(\tR\tfirstName\x12\x1b\n" +
	"\tlast_name\x18\x03 \x01(\tR\blastName\x12!\n" +
	"\fphone_number\x18\x04 \x01(\tR\vphoneNumber\x12E\n" +
	"\x10examination_date\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\x0fexaminationDate\x12\x10\n" +
	"\x03age\x18\x06 \x01(\x05R\x03age\x12!\n" +
	"\fprocedure_id\x18\a \x01(\rR\vprocedureId\x12'\n" +
	"\x0fother_procedure\x18\t \x01(\tR\x0eotherProcedure\x12\x1f\n" +
	"\vmodality_id\x18\n" +
	" \x01(\rR\n" +
	"modalityId\x12.\n" +
	"\x13referring_doctor_id\x18\f \x01(\rR\x11referringDoctorId\x12)\n" +
	"\x10clinical_history\x18\x0e \x01(\tR\x0fclinicalHistory\x12)\n" +
	"\x10referring_center\x18\x0f \x01(\tR\x0freferringCenter\x12\x10\n" +
	"\x03sex\x18\x10 \x01(\tR\x03sex\x12\x18\n" +
	"\aaddress\x18\x11 \x01(\tR\aaddress\x12(\n" +
	"\x10request_form_url\x18\x12 \x01(\tR\x0erequestFormUrl\x12\x19\n" +
	"\bis_moved\x18\x13 \x01(\bR\aisMoved\x12\x1d\n" +
	"\n" +
	"is_deleted\x18\x14 \x01(\bR\tisDeleted\x12!\n" +
	"\fis_completed\x18\x15 \x01(\bR\visCompleted\x129\n" +
	"\n" +
	"created_at\x18\x16 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x17 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAtB9Z7github.com/OtchereDev/ris-common-sdk/pkg/proto/referralb\x06proto3"

var (
	file_referral_proto_rawDescOnce sync.Once
	file_referral_proto_rawDescData []byte
)

func file_referral_proto_rawDescGZIP() []byte {
	file_referral_proto_rawDescOnce.Do(func() {
		file_referral_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_referral_proto_rawDesc), len(file_referral_proto_rawDesc)))
	})
	return file_referral_proto_rawDescData
}

var file_referral_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_referral_proto_goTypes = []any{
	(*ReferringCenter)(nil),           // 0: proto.ReferringCenter
	(*ReferringDoctor)(nil),           // 1: proto.ReferringDoctor
	(*DoctorLoggedIn)(nil),            // 2: proto.DoctorLoggedIn
	(*DoctorWalletPayCommission)(nil), // 3: proto.DoctorWalletPayCommission
	(*TempAppointment)(nil),           // 4: proto.TempAppointment
	(*timestamp.Timestamp)(nil),       // 5: google.protobuf.Timestamp
}
var file_referral_proto_depIdxs = []int32{
	0, // 0: proto.ReferringDoctor.referring_center:type_name -> proto.ReferringCenter
	5, // 1: proto.ReferringDoctor.last_login:type_name -> google.protobuf.Timestamp
	5, // 2: proto.ReferringDoctor.created_at:type_name -> google.protobuf.Timestamp
	5, // 3: proto.DoctorLoggedIn.time:type_name -> google.protobuf.Timestamp
	5, // 4: proto.TempAppointment.examination_date:type_name -> google.protobuf.Timestamp
	5, // 5: proto.TempAppointment.created_at:type_name -> google.protobuf.Timestamp
	5, // 6: proto.TempAppointment.updated_at:type_name -> google.protobuf.Timestamp
	7, // [7:7] is the sub-list for method output_type
	7, // [7:7] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_referral_proto_init() }
func file_referral_proto_init() {
	if File_referral_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_referral_proto_rawDesc), len(file_referral_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_referral_proto_goTypes,
		DependencyIndexes: file_referral_proto_depIdxs,
		MessageInfos:      file_referral_proto_msgTypes,
	}.Build()
	File_referral_proto = out.File
	file_referral_proto_goTypes = nil
	file_referral_proto_depIdxs = nil
}
