// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.12.4
// source: pkg/proto/user.proto

package users

import (
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type User struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Id                 uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	FirstName          string                 `protobuf:"bytes,2,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName           string                 `protobuf:"bytes,3,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	Email              string                 `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`
	LastLogin          *timestamp.Timestamp   `protobuf:"bytes,5,opt,name=last_login,json=lastLogin,proto3" json:"last_login,omitempty"`
	IsDisabled         bool                   `protobuf:"varint,6,opt,name=is_disabled,json=isDisabled,proto3" json:"is_disabled,omitempty"`
	IsDeleted          bool                   `protobuf:"varint,7,opt,name=is_deleted,json=isDeleted,proto3" json:"is_deleted,omitempty"`
	Role               string                 `protobuf:"bytes,8,opt,name=role,proto3" json:"role,omitempty"`
	TitleOnReport      string                 `protobuf:"bytes,9,opt,name=title_on_report,json=titleOnReport,proto3" json:"title_on_report,omitempty"`
	IsAdmin            bool                   `protobuf:"varint,10,opt,name=is_admin,json=isAdmin,proto3" json:"is_admin,omitempty"`
	CanVerify          bool                   `protobuf:"varint,11,opt,name=can_verify,json=canVerify,proto3" json:"can_verify,omitempty"`
	IsProxy            bool                   `protobuf:"varint,12,opt,name=is_proxy,json=isProxy,proto3" json:"is_proxy,omitempty"`
	SpecialAppointment bool                   `protobuf:"varint,13,opt,name=special_appointment,json=specialAppointment,proto3" json:"special_appointment,omitempty"`
	CreatedAt          *timestamp.Timestamp   `protobuf:"bytes,14,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt          *timestamp.Timestamp   `protobuf:"bytes,15,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	Password           string                 `protobuf:"bytes,16,opt,name=password,proto3" json:"password,omitempty"`
	PhoneNumber        string                 `protobuf:"bytes,17,opt,name=phone_number,json=phoneNumber,proto3" json:"phone_number,omitempty"`
	UseEmailOtp        bool                   `protobuf:"varint,18,opt,name=use_email_otp,json=useEmailOtp,proto3" json:"use_email_otp,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_pkg_proto_user_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_user_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_pkg_proto_user_proto_rawDescGZIP(), []int{0}
}

func (x *User) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *User) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *User) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

func (x *User) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *User) GetLastLogin() *timestamp.Timestamp {
	if x != nil {
		return x.LastLogin
	}
	return nil
}

func (x *User) GetIsDisabled() bool {
	if x != nil {
		return x.IsDisabled
	}
	return false
}

func (x *User) GetIsDeleted() bool {
	if x != nil {
		return x.IsDeleted
	}
	return false
}

func (x *User) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *User) GetTitleOnReport() string {
	if x != nil {
		return x.TitleOnReport
	}
	return ""
}

func (x *User) GetIsAdmin() bool {
	if x != nil {
		return x.IsAdmin
	}
	return false
}

func (x *User) GetCanVerify() bool {
	if x != nil {
		return x.CanVerify
	}
	return false
}

func (x *User) GetIsProxy() bool {
	if x != nil {
		return x.IsProxy
	}
	return false
}

func (x *User) GetSpecialAppointment() bool {
	if x != nil {
		return x.SpecialAppointment
	}
	return false
}

func (x *User) GetCreatedAt() *timestamp.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *User) GetUpdatedAt() *timestamp.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *User) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *User) GetPhoneNumber() string {
	if x != nil {
		return x.PhoneNumber
	}
	return ""
}

func (x *User) GetUseEmailOtp() bool {
	if x != nil {
		return x.UseEmailOtp
	}
	return false
}

var File_pkg_proto_user_proto protoreflect.FileDescriptor

const file_pkg_proto_user_proto_rawDesc = "" +
	"\n" +
	"\x14pkg/proto/user.proto\x12\x05proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xfe\x04\n" +
	"\x04User\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x1d\n" +
	"\n" +
	"first_name\x18\x02 \x01(\tR\tfirstName\x12\x1b\n" +
	"\tlast_name\x18\x03 \x01(\tR\blastName\x12\x14\n" +
	"\x05email\x18\x04 \x01(\tR\x05email\x129\n" +
	"\n" +
	"last_login\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tlastLogin\x12\x1f\n" +
	"\vis_disabled\x18\x06 \x01(\bR\n" +
	"isDisabled\x12\x1d\n" +
	"\n" +
	"is_deleted\x18\a \x01(\bR\tisDeleted\x12\x12\n" +
	"\x04role\x18\b \x01(\tR\x04role\x12&\n" +
	"\x0ftitle_on_report\x18\t \x01(\tR\rtitleOnReport\x12\x19\n" +
	"\bis_admin\x18\n" +
	" \x01(\bR\aisAdmin\x12\x1d\n" +
	"\n" +
	"can_verify\x18\v \x01(\bR\tcanVerify\x12\x19\n" +
	"\bis_proxy\x18\f \x01(\bR\aisProxy\x12/\n" +
	"\x13special_appointment\x18\r \x01(\bR\x12specialAppointment\x129\n" +
	"\n" +
	"created_at\x18\x0e \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x0f \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12\x1a\n" +
	"\bpassword\x18\x10 \x01(\tR\bpassword\x12!\n" +
	"\fphone_number\x18\x11 \x01(\tR\vphoneNumber\x12\"\n" +
	"\ruse_email_otp\x18\x12 \x01(\bR\vuseEmailOtpB\x11Z\x0fpkg/proto/usersb\x06proto3"

var (
	file_pkg_proto_user_proto_rawDescOnce sync.Once
	file_pkg_proto_user_proto_rawDescData []byte
)

func file_pkg_proto_user_proto_rawDescGZIP() []byte {
	file_pkg_proto_user_proto_rawDescOnce.Do(func() {
		file_pkg_proto_user_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_proto_user_proto_rawDesc), len(file_pkg_proto_user_proto_rawDesc)))
	})
	return file_pkg_proto_user_proto_rawDescData
}

var file_pkg_proto_user_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_pkg_proto_user_proto_goTypes = []any{
	(*User)(nil),                // 0: proto.User
	(*timestamp.Timestamp)(nil), // 1: google.protobuf.Timestamp
}
var file_pkg_proto_user_proto_depIdxs = []int32{
	1, // 0: proto.User.last_login:type_name -> google.protobuf.Timestamp
	1, // 1: proto.User.created_at:type_name -> google.protobuf.Timestamp
	1, // 2: proto.User.updated_at:type_name -> google.protobuf.Timestamp
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_pkg_proto_user_proto_init() }
func file_pkg_proto_user_proto_init() {
	if File_pkg_proto_user_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_proto_user_proto_rawDesc), len(file_pkg_proto_user_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pkg_proto_user_proto_goTypes,
		DependencyIndexes: file_pkg_proto_user_proto_depIdxs,
		MessageInfos:      file_pkg_proto_user_proto_msgTypes,
	}.Build()
	File_pkg_proto_user_proto = out.File
	file_pkg_proto_user_proto_goTypes = nil
	file_pkg_proto_user_proto_depIdxs = nil
}
