// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.12.4
// source: pkg/proto/payment.proto

package payment

import (
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Appointment Payment
type AppointmentPayment struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Id                  uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	AppointmentId       uint32                 `protobuf:"varint,2,opt,name=appointment_id,json=appointmentId,proto3" json:"appointment_id,omitempty"`
	TotalAmount         float64                `protobuf:"fixed64,4,opt,name=total_amount,json=totalAmount,proto3" json:"total_amount,omitempty"`
	HasDiscount         bool                   `protobuf:"varint,5,opt,name=has_discount,json=hasDiscount,proto3" json:"has_discount,omitempty"`
	IsReceipted         bool                   `protobuf:"varint,6,opt,name=is_receipted,json=isReceipted,proto3" json:"is_receipted,omitempty"`
	PaymentMethod       string                 `protobuf:"bytes,7,opt,name=payment_method,json=paymentMethod,proto3" json:"payment_method,omitempty"`
	DiscountAmount      float64                `protobuf:"fixed64,8,opt,name=discount_amount,json=discountAmount,proto3" json:"discount_amount,omitempty"`
	DiscountAuthorizer  string                 `protobuf:"bytes,9,opt,name=discount_authorizer,json=discountAuthorizer,proto3" json:"discount_authorizer,omitempty"`
	PaidAt              *timestamp.Timestamp   `protobuf:"bytes,10,opt,name=paid_at,json=paidAt,proto3" json:"paid_at,omitempty"`
	ReceiptNumber       string                 `protobuf:"bytes,11,opt,name=receipt_number,json=receiptNumber,proto3" json:"receipt_number,omitempty"`
	IsActive            bool                   `protobuf:"varint,12,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	ReplacedByPaymentId uint32                 `protobuf:"varint,13,opt,name=replaced_by_payment_id,json=replacedByPaymentId,proto3" json:"replaced_by_payment_id,omitempty"`
	Adjustments         []*PaymentAdjustment   `protobuf:"bytes,14,rep,name=adjustments,proto3" json:"adjustments,omitempty"`
	ReceiptUrl          string                 `protobuf:"bytes,15,opt,name=receipt_url,json=receiptUrl,proto3" json:"receipt_url,omitempty"`
	InsuranceCompany    string                 `protobuf:"bytes,16,opt,name=insurance_company,json=insuranceCompany,proto3" json:"insurance_company,omitempty"`
	InsuranceId         string                 `protobuf:"bytes,17,opt,name=insurance_id,json=insuranceId,proto3" json:"insurance_id,omitempty"`
	PaymentDetails      string                 `protobuf:"bytes,18,opt,name=payment_details,json=paymentDetails,proto3" json:"payment_details,omitempty"`
	InsuranerId         uint32                 `protobuf:"varint,19,opt,name=insuraner_id,json=insuranerId,proto3" json:"insuraner_id,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *AppointmentPayment) Reset() {
	*x = AppointmentPayment{}
	mi := &file_pkg_proto_payment_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppointmentPayment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppointmentPayment) ProtoMessage() {}

func (x *AppointmentPayment) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_payment_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppointmentPayment.ProtoReflect.Descriptor instead.
func (*AppointmentPayment) Descriptor() ([]byte, []int) {
	return file_pkg_proto_payment_proto_rawDescGZIP(), []int{0}
}

func (x *AppointmentPayment) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *AppointmentPayment) GetAppointmentId() uint32 {
	if x != nil {
		return x.AppointmentId
	}
	return 0
}

func (x *AppointmentPayment) GetTotalAmount() float64 {
	if x != nil {
		return x.TotalAmount
	}
	return 0
}

func (x *AppointmentPayment) GetHasDiscount() bool {
	if x != nil {
		return x.HasDiscount
	}
	return false
}

func (x *AppointmentPayment) GetIsReceipted() bool {
	if x != nil {
		return x.IsReceipted
	}
	return false
}

func (x *AppointmentPayment) GetPaymentMethod() string {
	if x != nil {
		return x.PaymentMethod
	}
	return ""
}

func (x *AppointmentPayment) GetDiscountAmount() float64 {
	if x != nil {
		return x.DiscountAmount
	}
	return 0
}

func (x *AppointmentPayment) GetDiscountAuthorizer() string {
	if x != nil {
		return x.DiscountAuthorizer
	}
	return ""
}

func (x *AppointmentPayment) GetPaidAt() *timestamp.Timestamp {
	if x != nil {
		return x.PaidAt
	}
	return nil
}

func (x *AppointmentPayment) GetReceiptNumber() string {
	if x != nil {
		return x.ReceiptNumber
	}
	return ""
}

func (x *AppointmentPayment) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

func (x *AppointmentPayment) GetReplacedByPaymentId() uint32 {
	if x != nil {
		return x.ReplacedByPaymentId
	}
	return 0
}

func (x *AppointmentPayment) GetAdjustments() []*PaymentAdjustment {
	if x != nil {
		return x.Adjustments
	}
	return nil
}

func (x *AppointmentPayment) GetReceiptUrl() string {
	if x != nil {
		return x.ReceiptUrl
	}
	return ""
}

func (x *AppointmentPayment) GetInsuranceCompany() string {
	if x != nil {
		return x.InsuranceCompany
	}
	return ""
}

func (x *AppointmentPayment) GetInsuranceId() string {
	if x != nil {
		return x.InsuranceId
	}
	return ""
}

func (x *AppointmentPayment) GetPaymentDetails() string {
	if x != nil {
		return x.PaymentDetails
	}
	return ""
}

func (x *AppointmentPayment) GetInsuranerId() uint32 {
	if x != nil {
		return x.InsuranerId
	}
	return 0
}

// Payment adjustment
type PaymentAdjustment struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Id                uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	OriginalPaymentId uint32                 `protobuf:"varint,2,opt,name=original_payment_id,json=originalPaymentId,proto3" json:"original_payment_id,omitempty"`
	NewPaymentId      uint32                 `protobuf:"varint,4,opt,name=new_payment_id,json=newPaymentId,proto3" json:"new_payment_id,omitempty"`
	AdjustmentType    string                 `protobuf:"bytes,6,opt,name=adjustment_type,json=adjustmentType,proto3" json:"adjustment_type,omitempty"`
	Amount            float64                `protobuf:"fixed64,7,opt,name=amount,proto3" json:"amount,omitempty"`
	PreviousAmount    float64                `protobuf:"fixed64,8,opt,name=previous_amount,json=previousAmount,proto3" json:"previous_amount,omitempty"`
	NewAmount         float64                `protobuf:"fixed64,9,opt,name=new_amount,json=newAmount,proto3" json:"new_amount,omitempty"`
	Reason            string                 `protobuf:"bytes,10,opt,name=reason,proto3" json:"reason,omitempty"`
	Status            string                 `protobuf:"bytes,11,opt,name=status,proto3" json:"status,omitempty"`
	ProcessedAt       *timestamp.Timestamp   `protobuf:"bytes,12,opt,name=processed_at,json=processedAt,proto3" json:"processed_at,omitempty"`
	ProcessedBy       uint32                 `protobuf:"varint,13,opt,name=processed_by,json=processedBy,proto3" json:"processed_by,omitempty"`
	CreatedAt         *timestamp.Timestamp   `protobuf:"bytes,14,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *PaymentAdjustment) Reset() {
	*x = PaymentAdjustment{}
	mi := &file_pkg_proto_payment_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaymentAdjustment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaymentAdjustment) ProtoMessage() {}

func (x *PaymentAdjustment) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_payment_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaymentAdjustment.ProtoReflect.Descriptor instead.
func (*PaymentAdjustment) Descriptor() ([]byte, []int) {
	return file_pkg_proto_payment_proto_rawDescGZIP(), []int{1}
}

func (x *PaymentAdjustment) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *PaymentAdjustment) GetOriginalPaymentId() uint32 {
	if x != nil {
		return x.OriginalPaymentId
	}
	return 0
}

func (x *PaymentAdjustment) GetNewPaymentId() uint32 {
	if x != nil {
		return x.NewPaymentId
	}
	return 0
}

func (x *PaymentAdjustment) GetAdjustmentType() string {
	if x != nil {
		return x.AdjustmentType
	}
	return ""
}

func (x *PaymentAdjustment) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *PaymentAdjustment) GetPreviousAmount() float64 {
	if x != nil {
		return x.PreviousAmount
	}
	return 0
}

func (x *PaymentAdjustment) GetNewAmount() float64 {
	if x != nil {
		return x.NewAmount
	}
	return 0
}

func (x *PaymentAdjustment) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *PaymentAdjustment) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *PaymentAdjustment) GetProcessedAt() *timestamp.Timestamp {
	if x != nil {
		return x.ProcessedAt
	}
	return nil
}

func (x *PaymentAdjustment) GetProcessedBy() uint32 {
	if x != nil {
		return x.ProcessedBy
	}
	return 0
}

func (x *PaymentAdjustment) GetCreatedAt() *timestamp.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

var File_pkg_proto_payment_proto protoreflect.FileDescriptor

const file_pkg_proto_payment_proto_rawDesc = "" +
	"\n" +
	"\x17pkg/proto/payment.proto\x12\vappointment\x1a\x1fgoogle/protobuf/timestamp.proto\"\xe2\x05\n" +
	"\x12AppointmentPayment\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12%\n" +
	"\x0eappointment_id\x18\x02 \x01(\rR\rappointmentId\x12!\n" +
	"\ftotal_amount\x18\x04 \x01(\x01R\vtotalAmount\x12!\n" +
	"\fhas_discount\x18\x05 \x01(\bR\vhasDiscount\x12!\n" +
	"\fis_receipted\x18\x06 \x01(\bR\visReceipted\x12%\n" +
	"\x0epayment_method\x18\a \x01(\tR\rpaymentMethod\x12'\n" +
	"\x0fdiscount_amount\x18\b \x01(\x01R\x0ediscountAmount\x12/\n" +
	"\x13discount_authorizer\x18\t \x01(\tR\x12discountAuthorizer\x123\n" +
	"\apaid_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\x06paidAt\x12%\n" +
	"\x0ereceipt_number\x18\v \x01(\tR\rreceiptNumber\x12\x1b\n" +
	"\tis_active\x18\f \x01(\bR\bisActive\x123\n" +
	"\x16replaced_by_payment_id\x18\r \x01(\rR\x13replacedByPaymentId\x12@\n" +
	"\vadjustments\x18\x0e \x03(\v2\x1e.appointment.PaymentAdjustmentR\vadjustments\x12\x1f\n" +
	"\vreceipt_url\x18\x0f \x01(\tR\n" +
	"receiptUrl\x12+\n" +
	"\x11insurance_company\x18\x10 \x01(\tR\x10insuranceCompany\x12!\n" +
	"\finsurance_id\x18\x11 \x01(\tR\vinsuranceId\x12'\n" +
	"\x0fpayment_details\x18\x12 \x01(\tR\x0epaymentDetails\x12!\n" +
	"\finsuraner_id\x18\x13 \x01(\rR\vinsuranerId\"\xcf\x03\n" +
	"\x11PaymentAdjustment\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12.\n" +
	"\x13original_payment_id\x18\x02 \x01(\rR\x11originalPaymentId\x12$\n" +
	"\x0enew_payment_id\x18\x04 \x01(\rR\fnewPaymentId\x12'\n" +
	"\x0fadjustment_type\x18\x06 \x01(\tR\x0eadjustmentType\x12\x16\n" +
	"\x06amount\x18\a \x01(\x01R\x06amount\x12'\n" +
	"\x0fprevious_amount\x18\b \x01(\x01R\x0epreviousAmount\x12\x1d\n" +
	"\n" +
	"new_amount\x18\t \x01(\x01R\tnewAmount\x12\x16\n" +
	"\x06reason\x18\n" +
	" \x01(\tR\x06reason\x12\x16\n" +
	"\x06status\x18\v \x01(\tR\x06status\x12=\n" +
	"\fprocessed_at\x18\f \x01(\v2\x1a.google.protobuf.TimestampR\vprocessedAt\x12!\n" +
	"\fprocessed_by\x18\r \x01(\rR\vprocessedBy\x129\n" +
	"\n" +
	"created_at\x18\x0e \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAtB\x13Z\x11pkg/proto/paymentb\x06proto3"

var (
	file_pkg_proto_payment_proto_rawDescOnce sync.Once
	file_pkg_proto_payment_proto_rawDescData []byte
)

func file_pkg_proto_payment_proto_rawDescGZIP() []byte {
	file_pkg_proto_payment_proto_rawDescOnce.Do(func() {
		file_pkg_proto_payment_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_proto_payment_proto_rawDesc), len(file_pkg_proto_payment_proto_rawDesc)))
	})
	return file_pkg_proto_payment_proto_rawDescData
}

var file_pkg_proto_payment_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_pkg_proto_payment_proto_goTypes = []any{
	(*AppointmentPayment)(nil),  // 0: appointment.AppointmentPayment
	(*PaymentAdjustment)(nil),   // 1: appointment.PaymentAdjustment
	(*timestamp.Timestamp)(nil), // 2: google.protobuf.Timestamp
}
var file_pkg_proto_payment_proto_depIdxs = []int32{
	2, // 0: appointment.AppointmentPayment.paid_at:type_name -> google.protobuf.Timestamp
	1, // 1: appointment.AppointmentPayment.adjustments:type_name -> appointment.PaymentAdjustment
	2, // 2: appointment.PaymentAdjustment.processed_at:type_name -> google.protobuf.Timestamp
	2, // 3: appointment.PaymentAdjustment.created_at:type_name -> google.protobuf.Timestamp
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_pkg_proto_payment_proto_init() }
func file_pkg_proto_payment_proto_init() {
	if File_pkg_proto_payment_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_proto_payment_proto_rawDesc), len(file_pkg_proto_payment_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pkg_proto_payment_proto_goTypes,
		DependencyIndexes: file_pkg_proto_payment_proto_depIdxs,
		MessageInfos:      file_pkg_proto_payment_proto_msgTypes,
	}.Build()
	File_pkg_proto_payment_proto = out.File
	file_pkg_proto_payment_proto_goTypes = nil
	file_pkg_proto_payment_proto_depIdxs = nil
}
