// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.12.4
// source: pkg/proto/notification.proto

package notification

import (
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type NotificationTemplate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	Priority      string                 `protobuf:"bytes,4,opt,name=priority,proto3" json:"priority,omitempty"`
	Category      string                 `protobuf:"bytes,5,opt,name=category,proto3" json:"category,omitempty"`
	ActionUrl     string                 `protobuf:"bytes,6,opt,name=action_url,json=actionUrl,proto3" json:"action_url,omitempty"`
	Metadata      string                 `protobuf:"bytes,7,opt,name=metadata,proto3" json:"metadata,omitempty"`
	ExpiresAt     *timestamp.Timestamp   `protobuf:"bytes,8,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	IsBroadcast   bool                   `protobuf:"varint,9,opt,name=is_broadcast,json=isBroadcast,proto3" json:"is_broadcast,omitempty"`
	TargetUsers   []string               `protobuf:"bytes,10,rep,name=target_users,json=targetUsers,proto3" json:"target_users,omitempty"`
	UserType      string                 `protobuf:"bytes,11,opt,name=user_type,json=userType,proto3" json:"user_type,omitempty"`
	PatientId     string                 `protobuf:"bytes,12,opt,name=patient_id,json=patientId,proto3" json:"patient_id,omitempty"`
	AppointmentId string                 `protobuf:"bytes,13,opt,name=appointment_id,json=appointmentId,proto3" json:"appointment_id,omitempty"`
	Urgency       bool                   `protobuf:"varint,14,opt,name=urgency,proto3" json:"urgency,omitempty"`
	CreatedAt     *timestamp.Timestamp   `protobuf:"bytes,15,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	CreatedBy     string                 `protobuf:"bytes,16,opt,name=created_by,json=createdBy,proto3" json:"created_by,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NotificationTemplate) Reset() {
	*x = NotificationTemplate{}
	mi := &file_pkg_proto_notification_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotificationTemplate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotificationTemplate) ProtoMessage() {}

func (x *NotificationTemplate) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_notification_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotificationTemplate.ProtoReflect.Descriptor instead.
func (*NotificationTemplate) Descriptor() ([]byte, []int) {
	return file_pkg_proto_notification_proto_rawDescGZIP(), []int{0}
}

func (x *NotificationTemplate) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *NotificationTemplate) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *NotificationTemplate) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *NotificationTemplate) GetPriority() string {
	if x != nil {
		return x.Priority
	}
	return ""
}

func (x *NotificationTemplate) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *NotificationTemplate) GetActionUrl() string {
	if x != nil {
		return x.ActionUrl
	}
	return ""
}

func (x *NotificationTemplate) GetMetadata() string {
	if x != nil {
		return x.Metadata
	}
	return ""
}

func (x *NotificationTemplate) GetExpiresAt() *timestamp.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

func (x *NotificationTemplate) GetIsBroadcast() bool {
	if x != nil {
		return x.IsBroadcast
	}
	return false
}

func (x *NotificationTemplate) GetTargetUsers() []string {
	if x != nil {
		return x.TargetUsers
	}
	return nil
}

func (x *NotificationTemplate) GetUserType() string {
	if x != nil {
		return x.UserType
	}
	return ""
}

func (x *NotificationTemplate) GetPatientId() string {
	if x != nil {
		return x.PatientId
	}
	return ""
}

func (x *NotificationTemplate) GetAppointmentId() string {
	if x != nil {
		return x.AppointmentId
	}
	return ""
}

func (x *NotificationTemplate) GetUrgency() bool {
	if x != nil {
		return x.Urgency
	}
	return false
}

func (x *NotificationTemplate) GetCreatedAt() *timestamp.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *NotificationTemplate) GetCreatedBy() string {
	if x != nil {
		return x.CreatedBy
	}
	return ""
}

var File_pkg_proto_notification_proto protoreflect.FileDescriptor

const file_pkg_proto_notification_proto_rawDesc = "" +
	"\n" +
	"\x1cpkg/proto/notification.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xa1\x04\n" +
	"\x14NotificationTemplate\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12\x1a\n" +
	"\bpriority\x18\x04 \x01(\tR\bpriority\x12\x1a\n" +
	"\bcategory\x18\x05 \x01(\tR\bcategory\x12\x1d\n" +
	"\n" +
	"action_url\x18\x06 \x01(\tR\tactionUrl\x12\x1a\n" +
	"\bmetadata\x18\a \x01(\tR\bmetadata\x129\n" +
	"\n" +
	"expires_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\x12!\n" +
	"\fis_broadcast\x18\t \x01(\bR\visBroadcast\x12!\n" +
	"\ftarget_users\x18\n" +
	" \x03(\tR\vtargetUsers\x12\x1b\n" +
	"\tuser_type\x18\v \x01(\tR\buserType\x12\x1d\n" +
	"\n" +
	"patient_id\x18\f \x01(\tR\tpatientId\x12%\n" +
	"\x0eappointment_id\x18\r \x01(\tR\rappointmentId\x12\x18\n" +
	"\aurgency\x18\x0e \x01(\bR\aurgency\x129\n" +
	"\n" +
	"created_at\x18\x0f \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"created_by\x18\x10 \x01(\tR\tcreatedByB\x18Z\x16pkg/proto/notificationb\x06proto3"

var (
	file_pkg_proto_notification_proto_rawDescOnce sync.Once
	file_pkg_proto_notification_proto_rawDescData []byte
)

func file_pkg_proto_notification_proto_rawDescGZIP() []byte {
	file_pkg_proto_notification_proto_rawDescOnce.Do(func() {
		file_pkg_proto_notification_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_proto_notification_proto_rawDesc), len(file_pkg_proto_notification_proto_rawDesc)))
	})
	return file_pkg_proto_notification_proto_rawDescData
}

var file_pkg_proto_notification_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_pkg_proto_notification_proto_goTypes = []any{
	(*NotificationTemplate)(nil), // 0: NotificationTemplate
	(*timestamp.Timestamp)(nil),  // 1: google.protobuf.Timestamp
}
var file_pkg_proto_notification_proto_depIdxs = []int32{
	1, // 0: NotificationTemplate.expires_at:type_name -> google.protobuf.Timestamp
	1, // 1: NotificationTemplate.created_at:type_name -> google.protobuf.Timestamp
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_pkg_proto_notification_proto_init() }
func file_pkg_proto_notification_proto_init() {
	if File_pkg_proto_notification_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_proto_notification_proto_rawDesc), len(file_pkg_proto_notification_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pkg_proto_notification_proto_goTypes,
		DependencyIndexes: file_pkg_proto_notification_proto_depIdxs,
		MessageInfos:      file_pkg_proto_notification_proto_msgTypes,
	}.Build()
	File_pkg_proto_notification_proto = out.File
	file_pkg_proto_notification_proto_goTypes = nil
	file_pkg_proto_notification_proto_depIdxs = nil
}
