// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: pkg/proto/pdf.proto

package pdf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PaymentItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Quantity      int32                  `protobuf:"varint,3,opt,name=quantity,proto3" json:"quantity,omitempty"`
	UnitPrice     string                 `protobuf:"bytes,4,opt,name=unitPrice,proto3" json:"unitPrice,omitempty"`
	Amount        string                 `protobuf:"bytes,5,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PaymentItem) Reset() {
	*x = PaymentItem{}
	mi := &file_pkg_proto_pdf_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaymentItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaymentItem) ProtoMessage() {}

func (x *PaymentItem) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_pdf_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaymentItem.ProtoReflect.Descriptor instead.
func (*PaymentItem) Descriptor() ([]byte, []int) {
	return file_pkg_proto_pdf_proto_rawDescGZIP(), []int{0}
}

func (x *PaymentItem) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *PaymentItem) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *PaymentItem) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *PaymentItem) GetUnitPrice() string {
	if x != nil {
		return x.UnitPrice
	}
	return ""
}

func (x *PaymentItem) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

type ReceiptData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileName      string                 `protobuf:"bytes,1,opt,name=fileName,proto3" json:"fileName,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	PatientId     string                 `protobuf:"bytes,3,opt,name=patientId,proto3" json:"patientId,omitempty"`
	PaymentDate   string                 `protobuf:"bytes,4,opt,name=paymentDate,proto3" json:"paymentDate,omitempty"`
	ReceiptNumber string                 `protobuf:"bytes,5,opt,name=receiptNumber,proto3" json:"receiptNumber,omitempty"`
	PaymentMethod string                 `protobuf:"bytes,6,opt,name=paymentMethod,proto3" json:"paymentMethod,omitempty"`
	Discount      string                 `protobuf:"bytes,7,opt,name=discount,proto3" json:"discount,omitempty"`
	SubTotal      string                 `protobuf:"bytes,8,opt,name=subTotal,proto3" json:"subTotal,omitempty"`
	Total         string                 `protobuf:"bytes,9,opt,name=total,proto3" json:"total,omitempty"`
	PaymentItems  []*PaymentItem         `protobuf:"bytes,10,rep,name=paymentItems,proto3" json:"paymentItems,omitempty"`
	Id            uint32                 `protobuf:"varint,11,opt,name=id,proto3" json:"id,omitempty"`
	// Selects the header, footer and logo. Empty falls back to the default brand.
	BrandKey      string `protobuf:"bytes,12,opt,name=brandKey,proto3" json:"brandKey,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReceiptData) Reset() {
	*x = ReceiptData{}
	mi := &file_pkg_proto_pdf_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReceiptData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReceiptData) ProtoMessage() {}

func (x *ReceiptData) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_pdf_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReceiptData.ProtoReflect.Descriptor instead.
func (*ReceiptData) Descriptor() ([]byte, []int) {
	return file_pkg_proto_pdf_proto_rawDescGZIP(), []int{1}
}

func (x *ReceiptData) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

func (x *ReceiptData) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ReceiptData) GetPatientId() string {
	if x != nil {
		return x.PatientId
	}
	return ""
}

func (x *ReceiptData) GetPaymentDate() string {
	if x != nil {
		return x.PaymentDate
	}
	return ""
}

func (x *ReceiptData) GetReceiptNumber() string {
	if x != nil {
		return x.ReceiptNumber
	}
	return ""
}

func (x *ReceiptData) GetPaymentMethod() string {
	if x != nil {
		return x.PaymentMethod
	}
	return ""
}

func (x *ReceiptData) GetDiscount() string {
	if x != nil {
		return x.Discount
	}
	return ""
}

func (x *ReceiptData) GetSubTotal() string {
	if x != nil {
		return x.SubTotal
	}
	return ""
}

func (x *ReceiptData) GetTotal() string {
	if x != nil {
		return x.Total
	}
	return ""
}

func (x *ReceiptData) GetPaymentItems() []*PaymentItem {
	if x != nil {
		return x.PaymentItems
	}
	return nil
}

func (x *ReceiptData) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ReceiptData) GetBrandKey() string {
	if x != nil {
		return x.BrandKey
	}
	return ""
}

type RequestFormData struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Id                 uint32                 `protobuf:"varint,12,opt,name=id,proto3" json:"id,omitempty"`
	PatientName        string                 `protobuf:"bytes,1,opt,name=patientName,proto3" json:"patientName,omitempty"`
	Sex                string                 `protobuf:"bytes,2,opt,name=sex,proto3" json:"sex,omitempty"`
	Date               string                 `protobuf:"bytes,3,opt,name=date,proto3" json:"date,omitempty"`
	Age                string                 `protobuf:"bytes,4,opt,name=age,proto3" json:"age,omitempty"`
	PhoneNumber        string                 `protobuf:"bytes,5,opt,name=phoneNumber,proto3" json:"phoneNumber,omitempty"`
	Address            string                 `protobuf:"bytes,6,opt,name=address,proto3" json:"address,omitempty"`
	RequestingDoctor   string                 `protobuf:"bytes,7,opt,name=requestingDoctor,proto3" json:"requestingDoctor,omitempty"`
	RequestingFacility string                 `protobuf:"bytes,8,opt,name=requestingFacility,proto3" json:"requestingFacility,omitempty"`
	Examination        string                 `protobuf:"bytes,9,opt,name=examination,proto3" json:"examination,omitempty"`
	Query              string                 `protobuf:"bytes,10,opt,name=query,proto3" json:"query,omitempty"`
	FileName           string                 `protobuf:"bytes,11,opt,name=fileName,proto3" json:"fileName,omitempty"`
	// Selects the header, footer and logo. Empty falls back to the default brand.
	BrandKey      string `protobuf:"bytes,13,opt,name=brandKey,proto3" json:"brandKey,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestFormData) Reset() {
	*x = RequestFormData{}
	mi := &file_pkg_proto_pdf_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestFormData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestFormData) ProtoMessage() {}

func (x *RequestFormData) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_pdf_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestFormData.ProtoReflect.Descriptor instead.
func (*RequestFormData) Descriptor() ([]byte, []int) {
	return file_pkg_proto_pdf_proto_rawDescGZIP(), []int{2}
}

func (x *RequestFormData) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *RequestFormData) GetPatientName() string {
	if x != nil {
		return x.PatientName
	}
	return ""
}

func (x *RequestFormData) GetSex() string {
	if x != nil {
		return x.Sex
	}
	return ""
}

func (x *RequestFormData) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *RequestFormData) GetAge() string {
	if x != nil {
		return x.Age
	}
	return ""
}

func (x *RequestFormData) GetPhoneNumber() string {
	if x != nil {
		return x.PhoneNumber
	}
	return ""
}

func (x *RequestFormData) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *RequestFormData) GetRequestingDoctor() string {
	if x != nil {
		return x.RequestingDoctor
	}
	return ""
}

func (x *RequestFormData) GetRequestingFacility() string {
	if x != nil {
		return x.RequestingFacility
	}
	return ""
}

func (x *RequestFormData) GetExamination() string {
	if x != nil {
		return x.Examination
	}
	return ""
}

func (x *RequestFormData) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *RequestFormData) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

func (x *RequestFormData) GetBrandKey() string {
	if x != nil {
		return x.BrandKey
	}
	return ""
}

type ReportData struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Id                uint32                 `protobuf:"varint,19,opt,name=id,proto3" json:"id,omitempty"`
	Name              string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Dob               string                 `protobuf:"bytes,2,opt,name=dob,proto3" json:"dob,omitempty"`
	Age               string                 `protobuf:"bytes,3,opt,name=age,proto3" json:"age,omitempty"`
	PatientId         string                 `protobuf:"bytes,4,opt,name=patientId,proto3" json:"patientId,omitempty"`
	ReferringDoctor   string                 `protobuf:"bytes,5,opt,name=referringDoctor,proto3" json:"referringDoctor,omitempty"`
	ReferringFacility string                 `protobuf:"bytes,6,opt,name=referringFacility,proto3" json:"referringFacility,omitempty"`
	Detail            string                 `protobuf:"bytes,7,opt,name=detail,proto3" json:"detail,omitempty"`
	Procedure         string                 `protobuf:"bytes,8,opt,name=procedure,proto3" json:"procedure,omitempty"`
	ExaminationDate   string                 `protobuf:"bytes,9,opt,name=examinationDate,proto3" json:"examinationDate,omitempty"`
	Radiologist       string                 `protobuf:"bytes,10,opt,name=radiologist,proto3" json:"radiologist,omitempty"`
	VerifiedAt        string                 `protobuf:"bytes,11,opt,name=verifiedAt,proto3" json:"verifiedAt,omitempty"`
	FileName          string                 `protobuf:"bytes,12,opt,name=fileName,proto3" json:"fileName,omitempty"`
	TitleOnReport     string                 `protobuf:"bytes,13,opt,name=titleOnReport,proto3" json:"titleOnReport,omitempty"`
	Impressions       string                 `protobuf:"bytes,14,opt,name=impressions,proto3" json:"impressions,omitempty"`
	Findings          string                 `protobuf:"bytes,15,opt,name=findings,proto3" json:"findings,omitempty"`
	ApprovedBy        string                 `protobuf:"bytes,16,opt,name=approvedBy,proto3" json:"approvedBy,omitempty"`
	ApproverTitle     string                 `protobuf:"bytes,17,opt,name=approverTitle,proto3" json:"approverTitle,omitempty"`
	WithHeader        bool                   `protobuf:"varint,18,opt,name=withHeader,proto3" json:"withHeader,omitempty"`
	Recommendations   string                 `protobuf:"bytes,20,opt,name=recommendations,proto3" json:"recommendations,omitempty"`
	Type              string                 `protobuf:"bytes,21,opt,name=Type,proto3" json:"Type,omitempty"`
	Weight            string                 `protobuf:"bytes,22,opt,name=Weight,proto3" json:"Weight,omitempty"`
	Height            string                 `protobuf:"bytes,23,opt,name=Height,proto3" json:"Height,omitempty"`
	BloodPressure     string                 `protobuf:"bytes,24,opt,name=BloodPressure,proto3" json:"BloodPressure,omitempty"`
	Appendix          string                 `protobuf:"bytes,25,opt,name=appendix,proto3" json:"appendix,omitempty"`
	// Selects the header, footer and logo. Empty falls back to the default brand.
	BrandKey      string `protobuf:"bytes,26,opt,name=brandKey,proto3" json:"brandKey,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportData) Reset() {
	*x = ReportData{}
	mi := &file_pkg_proto_pdf_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportData) ProtoMessage() {}

func (x *ReportData) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_pdf_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportData.ProtoReflect.Descriptor instead.
func (*ReportData) Descriptor() ([]byte, []int) {
	return file_pkg_proto_pdf_proto_rawDescGZIP(), []int{3}
}

func (x *ReportData) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ReportData) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ReportData) GetDob() string {
	if x != nil {
		return x.Dob
	}
	return ""
}

func (x *ReportData) GetAge() string {
	if x != nil {
		return x.Age
	}
	return ""
}

func (x *ReportData) GetPatientId() string {
	if x != nil {
		return x.PatientId
	}
	return ""
}

func (x *ReportData) GetReferringDoctor() string {
	if x != nil {
		return x.ReferringDoctor
	}
	return ""
}

func (x *ReportData) GetReferringFacility() string {
	if x != nil {
		return x.ReferringFacility
	}
	return ""
}

func (x *ReportData) GetDetail() string {
	if x != nil {
		return x.Detail
	}
	return ""
}

func (x *ReportData) GetProcedure() string {
	if x != nil {
		return x.Procedure
	}
	return ""
}

func (x *ReportData) GetExaminationDate() string {
	if x != nil {
		return x.ExaminationDate
	}
	return ""
}

func (x *ReportData) GetRadiologist() string {
	if x != nil {
		return x.Radiologist
	}
	return ""
}

func (x *ReportData) GetVerifiedAt() string {
	if x != nil {
		return x.VerifiedAt
	}
	return ""
}

func (x *ReportData) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

func (x *ReportData) GetTitleOnReport() string {
	if x != nil {
		return x.TitleOnReport
	}
	return ""
}

func (x *ReportData) GetImpressions() string {
	if x != nil {
		return x.Impressions
	}
	return ""
}

func (x *ReportData) GetFindings() string {
	if x != nil {
		return x.Findings
	}
	return ""
}

func (x *ReportData) GetApprovedBy() string {
	if x != nil {
		return x.ApprovedBy
	}
	return ""
}

func (x *ReportData) GetApproverTitle() string {
	if x != nil {
		return x.ApproverTitle
	}
	return ""
}

func (x *ReportData) GetWithHeader() bool {
	if x != nil {
		return x.WithHeader
	}
	return false
}

func (x *ReportData) GetRecommendations() string {
	if x != nil {
		return x.Recommendations
	}
	return ""
}

func (x *ReportData) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ReportData) GetWeight() string {
	if x != nil {
		return x.Weight
	}
	return ""
}

func (x *ReportData) GetHeight() string {
	if x != nil {
		return x.Height
	}
	return ""
}

func (x *ReportData) GetBloodPressure() string {
	if x != nil {
		return x.BloodPressure
	}
	return ""
}

func (x *ReportData) GetAppendix() string {
	if x != nil {
		return x.Appendix
	}
	return ""
}

func (x *ReportData) GetBrandKey() string {
	if x != nil {
		return x.BrandKey
	}
	return ""
}

// One row of a released lab report.
type LabResultLine struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Investigation string                 `protobuf:"bytes,1,opt,name=investigation,proto3" json:"investigation,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	Unit          string                 `protobuf:"bytes,3,opt,name=unit,proto3" json:"unit,omitempty"`
	// The range that was applied when the result was entered, not a live lookup. May carry
	// newlines where a test bands by sex or age ("Female: 53 - 120\nMale: 71 - 140").
	ReferenceInterval string `protobuf:"bytes,4,opt,name=referenceInterval,proto3" json:"referenceInterval,omitempty"`
	// N, H, L, HH, LL or A. Drives the marker printed beside the value.
	Flag          string `protobuf:"bytes,5,opt,name=flag,proto3" json:"flag,omitempty"`
	IsCritical    bool   `protobuf:"varint,6,opt,name=isCritical,proto3" json:"isCritical,omitempty"`
	Comment       string `protobuf:"bytes,7,opt,name=comment,proto3" json:"comment,omitempty"`
	Method        string `protobuf:"bytes,8,opt,name=method,proto3" json:"method,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LabResultLine) Reset() {
	*x = LabResultLine{}
	mi := &file_pkg_proto_pdf_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LabResultLine) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LabResultLine) ProtoMessage() {}

func (x *LabResultLine) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_pdf_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LabResultLine.ProtoReflect.Descriptor instead.
func (*LabResultLine) Descriptor() ([]byte, []int) {
	return file_pkg_proto_pdf_proto_rawDescGZIP(), []int{4}
}

func (x *LabResultLine) GetInvestigation() string {
	if x != nil {
		return x.Investigation
	}
	return ""
}

func (x *LabResultLine) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *LabResultLine) GetUnit() string {
	if x != nil {
		return x.Unit
	}
	return ""
}

func (x *LabResultLine) GetReferenceInterval() string {
	if x != nil {
		return x.ReferenceInterval
	}
	return ""
}

func (x *LabResultLine) GetFlag() string {
	if x != nil {
		return x.Flag
	}
	return ""
}

func (x *LabResultLine) GetIsCritical() bool {
	if x != nil {
		return x.IsCritical
	}
	return false
}

func (x *LabResultLine) GetComment() string {
	if x != nil {
		return x.Comment
	}
	return ""
}

func (x *LabResultLine) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

type LabKeyValue struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Label         string                 `protobuf:"bytes,1,opt,name=label,proto3" json:"label,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LabKeyValue) Reset() {
	*x = LabKeyValue{}
	mi := &file_pkg_proto_pdf_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LabKeyValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LabKeyValue) ProtoMessage() {}

func (x *LabKeyValue) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_pdf_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LabKeyValue.ProtoReflect.Descriptor instead.
func (*LabKeyValue) Descriptor() ([]byte, []int) {
	return file_pkg_proto_pdf_proto_rawDescGZIP(), []int{5}
}

func (x *LabKeyValue) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *LabKeyValue) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

// A titled block of label/value rows. Used by examinations that report two blocks side by
// side rather than one table, urine routine examination being the one everybody has seen:
// macroscopic findings on the left, microscopic on the right.
type LabSection struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Rows          []*LabKeyValue         `protobuf:"bytes,2,rep,name=rows,proto3" json:"rows,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LabSection) Reset() {
	*x = LabSection{}
	mi := &file_pkg_proto_pdf_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LabSection) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LabSection) ProtoMessage() {}

func (x *LabSection) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_pdf_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LabSection.ProtoReflect.Descriptor instead.
func (*LabSection) Descriptor() ([]byte, []int) {
	return file_pkg_proto_pdf_proto_rawDescGZIP(), []int{6}
}

func (x *LabSection) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *LabSection) GetRows() []*LabKeyValue {
	if x != nil {
		return x.Rows
	}
	return nil
}

// A titled block of prose. Surgical pathology reports its findings as named sections of
// text — macroscopy, microscopy, diagnosis — rather than as rows, and each is authored
// separately by the pathologist, so they travel separately rather than as one blob.
type LabNarrativeSection struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Title string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	// HTML, as authored in the application's editor.
	Body string `protobuf:"bytes,2,opt,name=body,proto3" json:"body,omitempty"`
	// Printed as the headline block. The diagnosis, on a pathology report: the line the
	// clinician reads first, and the one the rest of the page exists to support.
	Emphasis      bool `protobuf:"varint,3,opt,name=emphasis,proto3" json:"emphasis,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LabNarrativeSection) Reset() {
	*x = LabNarrativeSection{}
	mi := &file_pkg_proto_pdf_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LabNarrativeSection) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LabNarrativeSection) ProtoMessage() {}

func (x *LabNarrativeSection) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_pdf_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LabNarrativeSection.ProtoReflect.Descriptor instead.
func (*LabNarrativeSection) Descriptor() ([]byte, []int) {
	return file_pkg_proto_pdf_proto_rawDescGZIP(), []int{7}
}

func (x *LabNarrativeSection) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *LabNarrativeSection) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

func (x *LabNarrativeSection) GetEmphasis() bool {
	if x != nil {
		return x.Emphasis
	}
	return false
}

// One panel, which is one page of the report.
type LabReportPanel struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Overrides the catalogue title when set.
	Title string           `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Lines []*LabResultLine `protobuf:"bytes,2,rep,name=lines,proto3" json:"lines,omitempty"`
	// Free HTML printed under the table. Overrides the catalogue's standing notes when set.
	Interpretation string `protobuf:"bytes,3,opt,name=interpretation,proto3" json:"interpretation,omitempty"`
	// Histopathology and cytology, which report prose rather than rows.
	Narrative string `protobuf:"bytes,4,opt,name=narrative,proto3" json:"narrative,omitempty"`
	// Catalogue key: KFT, LFT, LIPID, HBA1C, HBSAG, PSA, CARDIAC, TROPONIN_I, TROPONIN_T,
	// URIC_ACID, URINE_RE, FBS. Selects the page layout and the standing reference material
	// that belongs to the examination rather than to the patient.
	Code string `protobuf:"bytes,5,opt,name=code,proto3" json:"code,omitempty"`
	// Overrides the catalogue layout when set: numeric, qualitative, three_column, paired,
	// marker, narrative or surgical_pathology.
	Layout   string        `protobuf:"bytes,6,opt,name=layout,proto3" json:"layout,omitempty"`
	Sections []*LabSection `protobuf:"bytes,7,rep,name=sections,proto3" json:"sections,omitempty"`
	// The specimen this examination actually ran on. The report-level specimen lists every
	// specimen on the order, which is wrong on a page reporting one of them.
	Specimen string `protobuf:"bytes,8,opt,name=specimen,proto3" json:"specimen,omitempty"`
	// The request as it was received: path number, date of biopsy, date of receipt, nature
	// of operation, the question asked. Printed in the page's patient block, in the order
	// sent, rather than in a header of their own — two near-identical headers a few
	// millimetres apart is a page a reader has to check twice to be sure they are not
	// looking at two different specimens. Do not send a field the patient block already
	// carries: the organ is the `specimen` field above.
	RequestDetails []*LabKeyValue `protobuf:"bytes,9,rep,name=requestDetails,proto3" json:"requestDetails,omitempty"`
	// Clinical history and the diagnosis under consideration, as the clinician gave it.
	// HTML. This is the requesting side's account, not the pathologist's, which is why it
	// sits apart from the narrative sections below.
	ClinicalHistory string `protobuf:"bytes,10,opt,name=clinicalHistory,proto3" json:"clinicalHistory,omitempty"`
	// Macroscopy, microscopy, diagnosis. Falls back to `narrative` when empty, so a plain
	// histopathology report that carries one authored blob still renders.
	NarrativeSections []*LabNarrativeSection `protobuf:"bytes,11,rep,name=narrativeSections,proto3" json:"narrativeSections,omitempty"`
	// The synoptic block under the diagnosis: tumour dimensions, margins, node counts,
	// stage. Titled "Other features" on the lab's current report.
	Synoptic      *LabSection `protobuf:"bytes,12,opt,name=synoptic,proto3" json:"synoptic,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LabReportPanel) Reset() {
	*x = LabReportPanel{}
	mi := &file_pkg_proto_pdf_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LabReportPanel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LabReportPanel) ProtoMessage() {}

func (x *LabReportPanel) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_pdf_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LabReportPanel.ProtoReflect.Descriptor instead.
func (*LabReportPanel) Descriptor() ([]byte, []int) {
	return file_pkg_proto_pdf_proto_rawDescGZIP(), []int{8}
}

func (x *LabReportPanel) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *LabReportPanel) GetLines() []*LabResultLine {
	if x != nil {
		return x.Lines
	}
	return nil
}

func (x *LabReportPanel) GetInterpretation() string {
	if x != nil {
		return x.Interpretation
	}
	return ""
}

func (x *LabReportPanel) GetNarrative() string {
	if x != nil {
		return x.Narrative
	}
	return ""
}

func (x *LabReportPanel) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *LabReportPanel) GetLayout() string {
	if x != nil {
		return x.Layout
	}
	return ""
}

func (x *LabReportPanel) GetSections() []*LabSection {
	if x != nil {
		return x.Sections
	}
	return nil
}

func (x *LabReportPanel) GetSpecimen() string {
	if x != nil {
		return x.Specimen
	}
	return ""
}

func (x *LabReportPanel) GetRequestDetails() []*LabKeyValue {
	if x != nil {
		return x.RequestDetails
	}
	return nil
}

func (x *LabReportPanel) GetClinicalHistory() string {
	if x != nil {
		return x.ClinicalHistory
	}
	return ""
}

func (x *LabReportPanel) GetNarrativeSections() []*LabNarrativeSection {
	if x != nil {
		return x.NarrativeSections
	}
	return nil
}

func (x *LabReportPanel) GetSynoptic() *LabSection {
	if x != nil {
		return x.Synoptic
	}
	return nil
}

type LabReportData struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	Id           uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	FileName     string                 `protobuf:"bytes,2,opt,name=fileName,proto3" json:"fileName,omitempty"`
	PathNumber   string                 `protobuf:"bytes,3,opt,name=pathNumber,proto3" json:"pathNumber,omitempty"`
	PatientName  string                 `protobuf:"bytes,4,opt,name=patientName,proto3" json:"patientName,omitempty"`
	PatientId    string                 `protobuf:"bytes,5,opt,name=patientId,proto3" json:"patientId,omitempty"`
	Age          string                 `protobuf:"bytes,6,opt,name=age,proto3" json:"age,omitempty"`
	Sex          string                 `protobuf:"bytes,7,opt,name=sex,proto3" json:"sex,omitempty"`
	Specimen     string                 `protobuf:"bytes,8,opt,name=specimen,proto3" json:"specimen,omitempty"`
	SpecimenDate string                 `protobuf:"bytes,9,opt,name=specimenDate,proto3" json:"specimenDate,omitempty"`
	ReportNumber string                 `protobuf:"bytes,10,opt,name=reportNumber,proto3" json:"reportNumber,omitempty"`
	// Set when the release covered only part of the order. Prints a banner saying so.
	IsInterim         bool              `protobuf:"varint,11,opt,name=isInterim,proto3" json:"isInterim,omitempty"`
	SignedBy          string            `protobuf:"bytes,12,opt,name=signedBy,proto3" json:"signedBy,omitempty"`
	ReleasedAt        string            `protobuf:"bytes,13,opt,name=releasedAt,proto3" json:"releasedAt,omitempty"`
	ReferringDoctor   string            `protobuf:"bytes,14,opt,name=referringDoctor,proto3" json:"referringDoctor,omitempty"`
	ReferringFacility string            `protobuf:"bytes,15,opt,name=referringFacility,proto3" json:"referringFacility,omitempty"`
	Panels            []*LabReportPanel `protobuf:"bytes,16,rep,name=panels,proto3" json:"panels,omitempty"`
	// Selects the header, footer and logo. Empty falls back to the default brand.
	BrandKey      string `protobuf:"bytes,17,opt,name=brandKey,proto3" json:"brandKey,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LabReportData) Reset() {
	*x = LabReportData{}
	mi := &file_pkg_proto_pdf_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LabReportData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LabReportData) ProtoMessage() {}

func (x *LabReportData) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_pdf_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LabReportData.ProtoReflect.Descriptor instead.
func (*LabReportData) Descriptor() ([]byte, []int) {
	return file_pkg_proto_pdf_proto_rawDescGZIP(), []int{9}
}

func (x *LabReportData) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *LabReportData) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

func (x *LabReportData) GetPathNumber() string {
	if x != nil {
		return x.PathNumber
	}
	return ""
}

func (x *LabReportData) GetPatientName() string {
	if x != nil {
		return x.PatientName
	}
	return ""
}

func (x *LabReportData) GetPatientId() string {
	if x != nil {
		return x.PatientId
	}
	return ""
}

func (x *LabReportData) GetAge() string {
	if x != nil {
		return x.Age
	}
	return ""
}

func (x *LabReportData) GetSex() string {
	if x != nil {
		return x.Sex
	}
	return ""
}

func (x *LabReportData) GetSpecimen() string {
	if x != nil {
		return x.Specimen
	}
	return ""
}

func (x *LabReportData) GetSpecimenDate() string {
	if x != nil {
		return x.SpecimenDate
	}
	return ""
}

func (x *LabReportData) GetReportNumber() string {
	if x != nil {
		return x.ReportNumber
	}
	return ""
}

func (x *LabReportData) GetIsInterim() bool {
	if x != nil {
		return x.IsInterim
	}
	return false
}

func (x *LabReportData) GetSignedBy() string {
	if x != nil {
		return x.SignedBy
	}
	return ""
}

func (x *LabReportData) GetReleasedAt() string {
	if x != nil {
		return x.ReleasedAt
	}
	return ""
}

func (x *LabReportData) GetReferringDoctor() string {
	if x != nil {
		return x.ReferringDoctor
	}
	return ""
}

func (x *LabReportData) GetReferringFacility() string {
	if x != nil {
		return x.ReferringFacility
	}
	return ""
}

func (x *LabReportData) GetPanels() []*LabReportPanel {
	if x != nil {
		return x.Panels
	}
	return nil
}

func (x *LabReportData) GetBrandKey() string {
	if x != nil {
		return x.BrandKey
	}
	return ""
}

type PdfEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Event:
	//
	//	*PdfEvent_Receipt
	//	*PdfEvent_RequestForm
	//	*PdfEvent_Report
	//	*PdfEvent_LabReport
	Event         isPdfEvent_Event `protobuf_oneof:"event"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PdfEvent) Reset() {
	*x = PdfEvent{}
	mi := &file_pkg_proto_pdf_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PdfEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PdfEvent) ProtoMessage() {}

func (x *PdfEvent) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_pdf_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PdfEvent.ProtoReflect.Descriptor instead.
func (*PdfEvent) Descriptor() ([]byte, []int) {
	return file_pkg_proto_pdf_proto_rawDescGZIP(), []int{10}
}

func (x *PdfEvent) GetEvent() isPdfEvent_Event {
	if x != nil {
		return x.Event
	}
	return nil
}

func (x *PdfEvent) GetReceipt() *ReceiptData {
	if x != nil {
		if x, ok := x.Event.(*PdfEvent_Receipt); ok {
			return x.Receipt
		}
	}
	return nil
}

func (x *PdfEvent) GetRequestForm() *RequestFormData {
	if x != nil {
		if x, ok := x.Event.(*PdfEvent_RequestForm); ok {
			return x.RequestForm
		}
	}
	return nil
}

func (x *PdfEvent) GetReport() *ReportData {
	if x != nil {
		if x, ok := x.Event.(*PdfEvent_Report); ok {
			return x.Report
		}
	}
	return nil
}

func (x *PdfEvent) GetLabReport() *LabReportData {
	if x != nil {
		if x, ok := x.Event.(*PdfEvent_LabReport); ok {
			return x.LabReport
		}
	}
	return nil
}

type isPdfEvent_Event interface {
	isPdfEvent_Event()
}

type PdfEvent_Receipt struct {
	Receipt *ReceiptData `protobuf:"bytes,1,opt,name=receipt,proto3,oneof"`
}

type PdfEvent_RequestForm struct {
	RequestForm *RequestFormData `protobuf:"bytes,2,opt,name=requestForm,proto3,oneof"`
}

type PdfEvent_Report struct {
	Report *ReportData `protobuf:"bytes,3,opt,name=report,proto3,oneof"`
}

type PdfEvent_LabReport struct {
	LabReport *LabReportData `protobuf:"bytes,4,opt,name=labReport,proto3,oneof"`
}

func (*PdfEvent_Receipt) isPdfEvent_Event() {}

func (*PdfEvent_RequestForm) isPdfEvent_Event() {}

func (*PdfEvent_Report) isPdfEvent_Event() {}

func (*PdfEvent_LabReport) isPdfEvent_Event() {}

type FileUploaded struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileKey       string                 `protobuf:"bytes,1,opt,name=fileKey,proto3" json:"fileKey,omitempty"`
	Id            uint32                 `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileUploaded) Reset() {
	*x = FileUploaded{}
	mi := &file_pkg_proto_pdf_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileUploaded) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileUploaded) ProtoMessage() {}

func (x *FileUploaded) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_pdf_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileUploaded.ProtoReflect.Descriptor instead.
func (*FileUploaded) Descriptor() ([]byte, []int) {
	return file_pkg_proto_pdf_proto_rawDescGZIP(), []int{11}
}

func (x *FileUploaded) GetFileKey() string {
	if x != nil {
		return x.FileKey
	}
	return ""
}

func (x *FileUploaded) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

var File_pkg_proto_pdf_proto protoreflect.FileDescriptor

const file_pkg_proto_pdf_proto_rawDesc = "" +
	"\n" +
	"\x13pkg/proto/pdf.proto\x12\x05proto\"\x95\x01\n" +
	"\vPaymentItem\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x1a\n" +
	"\bquantity\x18\x03 \x01(\x05R\bquantity\x12\x1c\n" +
	"\tunitPrice\x18\x04 \x01(\tR\tunitPrice\x12\x16\n" +
	"\x06amount\x18\x05 \x01(\tR\x06amount\"\xfb\x02\n" +
	"\vReceiptData\x12\x1a\n" +
	"\bfileName\x18\x01 \x01(\tR\bfileName\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1c\n" +
	"\tpatientId\x18\x03 \x01(\tR\tpatientId\x12 \n" +
	"\vpaymentDate\x18\x04 \x01(\tR\vpaymentDate\x12$\n" +
	"\rreceiptNumber\x18\x05 \x01(\tR\rreceiptNumber\x12$\n" +
	"\rpaymentMethod\x18\x06 \x01(\tR\rpaymentMethod\x12\x1a\n" +
	"\bdiscount\x18\a \x01(\tR\bdiscount\x12\x1a\n" +
	"\bsubTotal\x18\b \x01(\tR\bsubTotal\x12\x14\n" +
	"\x05total\x18\t \x01(\tR\x05total\x126\n" +
	"\fpaymentItems\x18\n" +
	" \x03(\v2\x12.proto.PaymentItemR\fpaymentItems\x12\x0e\n" +
	"\x02id\x18\v \x01(\rR\x02id\x12\x1a\n" +
	"\bbrandKey\x18\f \x01(\tR\bbrandKey\"\x83\x03\n" +
	"\x0fRequestFormData\x12\x0e\n" +
	"\x02id\x18\f \x01(\rR\x02id\x12 \n" +
	"\vpatientName\x18\x01 \x01(\tR\vpatientName\x12\x10\n" +
	"\x03sex\x18\x02 \x01(\tR\x03sex\x12\x12\n" +
	"\x04date\x18\x03 \x01(\tR\x04date\x12\x10\n" +
	"\x03age\x18\x04 \x01(\tR\x03age\x12 \n" +
	"\vphoneNumber\x18\x05 \x01(\tR\vphoneNumber\x12\x18\n" +
	"\aaddress\x18\x06 \x01(\tR\aaddress\x12*\n" +
	"\x10requestingDoctor\x18\a \x01(\tR\x10requestingDoctor\x12.\n" +
	"\x12requestingFacility\x18\b \x01(\tR\x12requestingFacility\x12 \n" +
	"\vexamination\x18\t \x01(\tR\vexamination\x12\x14\n" +
	"\x05query\x18\n" +
	" \x01(\tR\x05query\x12\x1a\n" +
	"\bfileName\x18\v \x01(\tR\bfileName\x12\x1a\n" +
	"\bbrandKey\x18\r \x01(\tR\bbrandKey\"\x9e\x06\n" +
	"\n" +
	"ReportData\x12\x0e\n" +
	"\x02id\x18\x13 \x01(\rR\x02id\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x10\n" +
	"\x03dob\x18\x02 \x01(\tR\x03dob\x12\x10\n" +
	"\x03age\x18\x03 \x01(\tR\x03age\x12\x1c\n" +
	"\tpatientId\x18\x04 \x01(\tR\tpatientId\x12(\n" +
	"\x0freferringDoctor\x18\x05 \x01(\tR\x0freferringDoctor\x12,\n" +
	"\x11referringFacility\x18\x06 \x01(\tR\x11referringFacility\x12\x16\n" +
	"\x06detail\x18\a \x01(\tR\x06detail\x12\x1c\n" +
	"\tprocedure\x18\b \x01(\tR\tprocedure\x12(\n" +
	"\x0fexaminationDate\x18\t \x01(\tR\x0fexaminationDate\x12 \n" +
	"\vradiologist\x18\n" +
	" \x01(\tR\vradiologist\x12\x1e\n" +
	"\n" +
	"verifiedAt\x18\v \x01(\tR\n" +
	"verifiedAt\x12\x1a\n" +
	"\bfileName\x18\f \x01(\tR\bfileName\x12$\n" +
	"\rtitleOnReport\x18\r \x01(\tR\rtitleOnReport\x12 \n" +
	"\vimpressions\x18\x0e \x01(\tR\vimpressions\x12\x1a\n" +
	"\bfindings\x18\x0f \x01(\tR\bfindings\x12\x1e\n" +
	"\n" +
	"approvedBy\x18\x10 \x01(\tR\n" +
	"approvedBy\x12$\n" +
	"\rapproverTitle\x18\x11 \x01(\tR\rapproverTitle\x12\x1e\n" +
	"\n" +
	"withHeader\x18\x12 \x01(\bR\n" +
	"withHeader\x12(\n" +
	"\x0frecommendations\x18\x14 \x01(\tR\x0frecommendations\x12\x12\n" +
	"\x04Type\x18\x15 \x01(\tR\x04Type\x12\x16\n" +
	"\x06Weight\x18\x16 \x01(\tR\x06Weight\x12\x16\n" +
	"\x06Height\x18\x17 \x01(\tR\x06Height\x12$\n" +
	"\rBloodPressure\x18\x18 \x01(\tR\rBloodPressure\x12\x1a\n" +
	"\bappendix\x18\x19 \x01(\tR\bappendix\x12\x1a\n" +
	"\bbrandKey\x18\x1a \x01(\tR\bbrandKey\"\xf3\x01\n" +
	"\rLabResultLine\x12$\n" +
	"\rinvestigation\x18\x01 \x01(\tR\rinvestigation\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\x12\x12\n" +
	"\x04unit\x18\x03 \x01(\tR\x04unit\x12,\n" +
	"\x11referenceInterval\x18\x04 \x01(\tR\x11referenceInterval\x12\x12\n" +
	"\x04flag\x18\x05 \x01(\tR\x04flag\x12\x1e\n" +
	"\n" +
	"isCritical\x18\x06 \x01(\bR\n" +
	"isCritical\x12\x18\n" +
	"\acomment\x18\a \x01(\tR\acomment\x12\x16\n" +
	"\x06method\x18\b \x01(\tR\x06method\"9\n" +
	"\vLabKeyValue\x12\x14\n" +
	"\x05label\x18\x01 \x01(\tR\x05label\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\"J\n" +
	"\n" +
	"LabSection\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12&\n" +
	"\x04rows\x18\x02 \x03(\v2\x12.proto.LabKeyValueR\x04rows\"[\n" +
	"\x13LabNarrativeSection\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12\x12\n" +
	"\x04body\x18\x02 \x01(\tR\x04body\x12\x1a\n" +
	"\bemphasis\x18\x03 \x01(\bR\bemphasis\"\xee\x03\n" +
	"\x0eLabReportPanel\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12*\n" +
	"\x05lines\x18\x02 \x03(\v2\x14.proto.LabResultLineR\x05lines\x12&\n" +
	"\x0einterpretation\x18\x03 \x01(\tR\x0einterpretation\x12\x1c\n" +
	"\tnarrative\x18\x04 \x01(\tR\tnarrative\x12\x12\n" +
	"\x04code\x18\x05 \x01(\tR\x04code\x12\x16\n" +
	"\x06layout\x18\x06 \x01(\tR\x06layout\x12-\n" +
	"\bsections\x18\a \x03(\v2\x11.proto.LabSectionR\bsections\x12\x1a\n" +
	"\bspecimen\x18\b \x01(\tR\bspecimen\x12:\n" +
	"\x0erequestDetails\x18\t \x03(\v2\x12.proto.LabKeyValueR\x0erequestDetails\x12(\n" +
	"\x0fclinicalHistory\x18\n" +
	" \x01(\tR\x0fclinicalHistory\x12H\n" +
	"\x11narrativeSections\x18\v \x03(\v2\x1a.proto.LabNarrativeSectionR\x11narrativeSections\x12-\n" +
	"\bsynoptic\x18\f \x01(\v2\x11.proto.LabSectionR\bsynoptic\"\xa0\x04\n" +
	"\rLabReportData\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x1a\n" +
	"\bfileName\x18\x02 \x01(\tR\bfileName\x12\x1e\n" +
	"\n" +
	"pathNumber\x18\x03 \x01(\tR\n" +
	"pathNumber\x12 \n" +
	"\vpatientName\x18\x04 \x01(\tR\vpatientName\x12\x1c\n" +
	"\tpatientId\x18\x05 \x01(\tR\tpatientId\x12\x10\n" +
	"\x03age\x18\x06 \x01(\tR\x03age\x12\x10\n" +
	"\x03sex\x18\a \x01(\tR\x03sex\x12\x1a\n" +
	"\bspecimen\x18\b \x01(\tR\bspecimen\x12\"\n" +
	"\fspecimenDate\x18\t \x01(\tR\fspecimenDate\x12\"\n" +
	"\freportNumber\x18\n" +
	" \x01(\tR\freportNumber\x12\x1c\n" +
	"\tisInterim\x18\v \x01(\bR\tisInterim\x12\x1a\n" +
	"\bsignedBy\x18\f \x01(\tR\bsignedBy\x12\x1e\n" +
	"\n" +
	"releasedAt\x18\r \x01(\tR\n" +
	"releasedAt\x12(\n" +
	"\x0freferringDoctor\x18\x0e \x01(\tR\x0freferringDoctor\x12,\n" +
	"\x11referringFacility\x18\x0f \x01(\tR\x11referringFacility\x12-\n" +
	"\x06panels\x18\x10 \x03(\v2\x15.proto.LabReportPanelR\x06panels\x12\x1a\n" +
	"\bbrandKey\x18\x11 \x01(\tR\bbrandKey\"\xe2\x01\n" +
	"\bPdfEvent\x12.\n" +
	"\areceipt\x18\x01 \x01(\v2\x12.proto.ReceiptDataH\x00R\areceipt\x12:\n" +
	"\vrequestForm\x18\x02 \x01(\v2\x16.proto.RequestFormDataH\x00R\vrequestForm\x12+\n" +
	"\x06report\x18\x03 \x01(\v2\x11.proto.ReportDataH\x00R\x06report\x124\n" +
	"\tlabReport\x18\x04 \x01(\v2\x14.proto.LabReportDataH\x00R\tlabReportB\a\n" +
	"\x05event\"8\n" +
	"\fFileUploaded\x12\x18\n" +
	"\afileKey\x18\x01 \x01(\tR\afileKey\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\rR\x02idB\x0fZ\rpkg/proto/pdfb\x06proto3"

var (
	file_pkg_proto_pdf_proto_rawDescOnce sync.Once
	file_pkg_proto_pdf_proto_rawDescData []byte
)

func file_pkg_proto_pdf_proto_rawDescGZIP() []byte {
	file_pkg_proto_pdf_proto_rawDescOnce.Do(func() {
		file_pkg_proto_pdf_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_proto_pdf_proto_rawDesc), len(file_pkg_proto_pdf_proto_rawDesc)))
	})
	return file_pkg_proto_pdf_proto_rawDescData
}

var file_pkg_proto_pdf_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_pkg_proto_pdf_proto_goTypes = []any{
	(*PaymentItem)(nil),         // 0: proto.PaymentItem
	(*ReceiptData)(nil),         // 1: proto.ReceiptData
	(*RequestFormData)(nil),     // 2: proto.RequestFormData
	(*ReportData)(nil),          // 3: proto.ReportData
	(*LabResultLine)(nil),       // 4: proto.LabResultLine
	(*LabKeyValue)(nil),         // 5: proto.LabKeyValue
	(*LabSection)(nil),          // 6: proto.LabSection
	(*LabNarrativeSection)(nil), // 7: proto.LabNarrativeSection
	(*LabReportPanel)(nil),      // 8: proto.LabReportPanel
	(*LabReportData)(nil),       // 9: proto.LabReportData
	(*PdfEvent)(nil),            // 10: proto.PdfEvent
	(*FileUploaded)(nil),        // 11: proto.FileUploaded
}
var file_pkg_proto_pdf_proto_depIdxs = []int32{
	0,  // 0: proto.ReceiptData.paymentItems:type_name -> proto.PaymentItem
	5,  // 1: proto.LabSection.rows:type_name -> proto.LabKeyValue
	4,  // 2: proto.LabReportPanel.lines:type_name -> proto.LabResultLine
	6,  // 3: proto.LabReportPanel.sections:type_name -> proto.LabSection
	5,  // 4: proto.LabReportPanel.requestDetails:type_name -> proto.LabKeyValue
	7,  // 5: proto.LabReportPanel.narrativeSections:type_name -> proto.LabNarrativeSection
	6,  // 6: proto.LabReportPanel.synoptic:type_name -> proto.LabSection
	8,  // 7: proto.LabReportData.panels:type_name -> proto.LabReportPanel
	1,  // 8: proto.PdfEvent.receipt:type_name -> proto.ReceiptData
	2,  // 9: proto.PdfEvent.requestForm:type_name -> proto.RequestFormData
	3,  // 10: proto.PdfEvent.report:type_name -> proto.ReportData
	9,  // 11: proto.PdfEvent.labReport:type_name -> proto.LabReportData
	12, // [12:12] is the sub-list for method output_type
	12, // [12:12] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_pkg_proto_pdf_proto_init() }
func file_pkg_proto_pdf_proto_init() {
	if File_pkg_proto_pdf_proto != nil {
		return
	}
	file_pkg_proto_pdf_proto_msgTypes[10].OneofWrappers = []any{
		(*PdfEvent_Receipt)(nil),
		(*PdfEvent_RequestForm)(nil),
		(*PdfEvent_Report)(nil),
		(*PdfEvent_LabReport)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_proto_pdf_proto_rawDesc), len(file_pkg_proto_pdf_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pkg_proto_pdf_proto_goTypes,
		DependencyIndexes: file_pkg_proto_pdf_proto_depIdxs,
		MessageInfos:      file_pkg_proto_pdf_proto_msgTypes,
	}.Build()
	File_pkg_proto_pdf_proto = out.File
	file_pkg_proto_pdf_proto_goTypes = nil
	file_pkg_proto_pdf_proto_depIdxs = nil
}
