// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: pkg/proto/center.proto

package center

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Center struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	IsDeleted     bool                   `protobuf:"varint,3,opt,name=is_deleted,json=isDeleted,proto3" json:"is_deleted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Center) Reset() {
	*x = Center{}
	mi := &file_pkg_proto_center_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Center) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Center) ProtoMessage() {}

func (x *Center) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_center_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Center.ProtoReflect.Descriptor instead.
func (*Center) Descriptor() ([]byte, []int) {
	return file_pkg_proto_center_proto_rawDescGZIP(), []int{0}
}

func (x *Center) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Center) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Center) GetIsDeleted() bool {
	if x != nil {
		return x.IsDeleted
	}
	return false
}

type ModalityCenterChange struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Action        string                 `protobuf:"bytes,1,opt,name=action,proto3" json:"action,omitempty"` // add or removed
	Centers       []string               `protobuf:"bytes,2,rep,name=centers,proto3" json:"centers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ModalityCenterChange) Reset() {
	*x = ModalityCenterChange{}
	mi := &file_pkg_proto_center_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModalityCenterChange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModalityCenterChange) ProtoMessage() {}

func (x *ModalityCenterChange) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_center_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModalityCenterChange.ProtoReflect.Descriptor instead.
func (*ModalityCenterChange) Descriptor() ([]byte, []int) {
	return file_pkg_proto_center_proto_rawDescGZIP(), []int{1}
}

func (x *ModalityCenterChange) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *ModalityCenterChange) GetCenters() []string {
	if x != nil {
		return x.Centers
	}
	return nil
}

var File_pkg_proto_center_proto protoreflect.FileDescriptor

const file_pkg_proto_center_proto_rawDesc = "" +
	"\n" +
	"\x16pkg/proto/center.proto\x12\x05proto\"K\n" +
	"\x06Center\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1d\n" +
	"\n" +
	"is_deleted\x18\x03 \x01(\bR\tisDeleted\"H\n" +
	"\x14ModalityCenterChange\x12\x16\n" +
	"\x06action\x18\x01 \x01(\tR\x06action\x12\x18\n" +
	"\acenters\x18\x02 \x03(\tR\acentersB\x12Z\x10pkg/proto/centerb\x06proto3"

var (
	file_pkg_proto_center_proto_rawDescOnce sync.Once
	file_pkg_proto_center_proto_rawDescData []byte
)

func file_pkg_proto_center_proto_rawDescGZIP() []byte {
	file_pkg_proto_center_proto_rawDescOnce.Do(func() {
		file_pkg_proto_center_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_proto_center_proto_rawDesc), len(file_pkg_proto_center_proto_rawDesc)))
	})
	return file_pkg_proto_center_proto_rawDescData
}

var file_pkg_proto_center_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_pkg_proto_center_proto_goTypes = []any{
	(*Center)(nil),               // 0: proto.Center
	(*ModalityCenterChange)(nil), // 1: proto.ModalityCenterChange
}
var file_pkg_proto_center_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pkg_proto_center_proto_init() }
func file_pkg_proto_center_proto_init() {
	if File_pkg_proto_center_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_proto_center_proto_rawDesc), len(file_pkg_proto_center_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pkg_proto_center_proto_goTypes,
		DependencyIndexes: file_pkg_proto_center_proto_depIdxs,
		MessageInfos:      file_pkg_proto_center_proto_msgTypes,
	}.Build()
	File_pkg_proto_center_proto = out.File
	file_pkg_proto_center_proto_goTypes = nil
	file_pkg_proto_center_proto_depIdxs = nil
}
