// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.12.4
// source: patient.proto

package patient

import (
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Patient struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`                                                        // Use uint32 for ID since protobuf doesn't support uint directly
	PatientId        string                 `protobuf:"bytes,2,opt,name=patient_id,json=patientId,proto3" json:"patient_id,omitempty"`                          // Unique identifier
	FirstName        string                 `protobuf:"bytes,3,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`                          // Required first name
	LastName         string                 `protobuf:"bytes,4,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`                             // Required last name
	PhoneNumber      string                 `protobuf:"bytes,5,opt,name=phone_number,json=phoneNumber,proto3" json:"phone_number,omitempty"`                    // Required phone number
	Gender           string                 `protobuf:"bytes,6,opt,name=gender,proto3" json:"gender,omitempty"`                                                 // Gender (nullable)
	Email            string                 `protobuf:"bytes,7,opt,name=email,proto3" json:"email,omitempty"`                                                   // Nullable email
	DeviceId         string                 `protobuf:"bytes,8,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`                             // Nullable device ID
	Address          string                 `protobuf:"bytes,9,opt,name=address,proto3" json:"address,omitempty"`                                               // Nullable address
	Dob              *timestamp.Timestamp   `protobuf:"bytes,10,opt,name=dob,proto3" json:"dob,omitempty"`                                                      // Date of birth
	AllowMobileLogin bool                   `protobuf:"varint,11,opt,name=allow_mobile_login,json=allowMobileLogin,proto3" json:"allow_mobile_login,omitempty"` // Default: true
	IsDeleted        bool                   `protobuf:"varint,12,opt,name=is_deleted,json=isDeleted,proto3" json:"is_deleted,omitempty"`                        // Default: false
	CreatedAt        *timestamp.Timestamp   `protobuf:"bytes,13,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`                         // Automatically created timestamp
	UpdatedAt        *timestamp.Timestamp   `protobuf:"bytes,14,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`                         // Automatically updated timestamp
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Patient) Reset() {
	*x = Patient{}
	mi := &file_patient_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Patient) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Patient) ProtoMessage() {}

func (x *Patient) ProtoReflect() protoreflect.Message {
	mi := &file_patient_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Patient.ProtoReflect.Descriptor instead.
func (*Patient) Descriptor() ([]byte, []int) {
	return file_patient_proto_rawDescGZIP(), []int{0}
}

func (x *Patient) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Patient) GetPatientId() string {
	if x != nil {
		return x.PatientId
	}
	return ""
}

func (x *Patient) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *Patient) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

func (x *Patient) GetPhoneNumber() string {
	if x != nil {
		return x.PhoneNumber
	}
	return ""
}

func (x *Patient) GetGender() string {
	if x != nil {
		return x.Gender
	}
	return ""
}

func (x *Patient) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *Patient) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *Patient) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *Patient) GetDob() *timestamp.Timestamp {
	if x != nil {
		return x.Dob
	}
	return nil
}

func (x *Patient) GetAllowMobileLogin() bool {
	if x != nil {
		return x.AllowMobileLogin
	}
	return false
}

func (x *Patient) GetIsDeleted() bool {
	if x != nil {
		return x.IsDeleted
	}
	return false
}

func (x *Patient) GetCreatedAt() *timestamp.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Patient) GetUpdatedAt() *timestamp.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type UpdatePatientDeviceId struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	DeviceId      string                 `protobuf:"bytes,2,opt,name=deviceId,proto3" json:"deviceId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdatePatientDeviceId) Reset() {
	*x = UpdatePatientDeviceId{}
	mi := &file_patient_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePatientDeviceId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePatientDeviceId) ProtoMessage() {}

func (x *UpdatePatientDeviceId) ProtoReflect() protoreflect.Message {
	mi := &file_patient_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePatientDeviceId.ProtoReflect.Descriptor instead.
func (*UpdatePatientDeviceId) Descriptor() ([]byte, []int) {
	return file_patient_proto_rawDescGZIP(), []int{1}
}

func (x *UpdatePatientDeviceId) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdatePatientDeviceId) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

var File_patient_proto protoreflect.FileDescriptor

const file_patient_proto_rawDesc = "" +
	"\n" +
	"\rpatient.proto\x12\x05proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xed\x03\n" +
	"\aPatient\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x1d\n" +
	"\n" +
	"patient_id\x18\x02 \x01(\tR\tpatientId\x12\x1d\n" +
	"\n" +
	"first_name\x18\x03 \x01(\tR\tfirstName\x12\x1b\n" +
	"\tlast_name\x18\x04 \x01(\tR\blastName\x12!\n" +
	"\fphone_number\x18\x05 \x01(\tR\vphoneNumber\x12\x16\n" +
	"\x06gender\x18\x06 \x01(\tR\x06gender\x12\x14\n" +
	"\x05email\x18\a \x01(\tR\x05email\x12\x1b\n" +
	"\tdevice_id\x18\b \x01(\tR\bdeviceId\x12\x18\n" +
	"\aaddress\x18\t \x01(\tR\aaddress\x12,\n" +
	"\x03dob\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\x03dob\x12,\n" +
	"\x12allow_mobile_login\x18\v \x01(\bR\x10allowMobileLogin\x12\x1d\n" +
	"\n" +
	"is_deleted\x18\f \x01(\bR\tisDeleted\x129\n" +
	"\n" +
	"created_at\x18\r \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x0e \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"C\n" +
	"\x15UpdatePatientDeviceId\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x1a\n" +
	"\bdeviceId\x18\x02 \x01(\tR\bdeviceIdB8Z6github.com/OtchereDev/ris-common-sdk/pkg/proto/patientb\x06proto3"

var (
	file_patient_proto_rawDescOnce sync.Once
	file_patient_proto_rawDescData []byte
)

func file_patient_proto_rawDescGZIP() []byte {
	file_patient_proto_rawDescOnce.Do(func() {
		file_patient_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_patient_proto_rawDesc), len(file_patient_proto_rawDesc)))
	})
	return file_patient_proto_rawDescData
}

var file_patient_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_patient_proto_goTypes = []any{
	(*Patient)(nil),               // 0: proto.Patient
	(*UpdatePatientDeviceId)(nil), // 1: proto.UpdatePatientDeviceId
	(*timestamp.Timestamp)(nil),   // 2: google.protobuf.Timestamp
}
var file_patient_proto_depIdxs = []int32{
	2, // 0: proto.Patient.dob:type_name -> google.protobuf.Timestamp
	2, // 1: proto.Patient.created_at:type_name -> google.protobuf.Timestamp
	2, // 2: proto.Patient.updated_at:type_name -> google.protobuf.Timestamp
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_patient_proto_init() }
func file_patient_proto_init() {
	if File_patient_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_patient_proto_rawDesc), len(file_patient_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_patient_proto_goTypes,
		DependencyIndexes: file_patient_proto_depIdxs,
		MessageInfos:      file_patient_proto_msgTypes,
	}.Build()
	File_patient_proto = out.File
	file_patient_proto_goTypes = nil
	file_patient_proto_depIdxs = nil
}
