// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.12.4
// source: pkg/proto/mws.proto

package worklist

import (
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateWorklistEntry struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	PatientId           string                 `protobuf:"bytes,1,opt,name=patient_id,json=patientId,proto3" json:"patient_id,omitempty"`
	PatientName         string                 `protobuf:"bytes,2,opt,name=patient_name,json=patientName,proto3" json:"patient_name,omitempty"`
	PatientBirthDate    *timestamp.Timestamp   `protobuf:"bytes,3,opt,name=patient_birth_date,json=patientBirthDate,proto3" json:"patient_birth_date,omitempty"`
	PatientSex          string                 `protobuf:"bytes,4,opt,name=patient_sex,json=patientSex,proto3" json:"patient_sex,omitempty"`
	StudyInstanceUid    string                 `protobuf:"bytes,5,opt,name=study_instance_uid,json=studyInstanceUid,proto3" json:"study_instance_uid,omitempty"`
	SpsId               string                 `protobuf:"bytes,6,opt,name=sps_id,json=spsId,proto3" json:"sps_id,omitempty"`
	SpsStartDate        *timestamp.Timestamp   `protobuf:"bytes,7,opt,name=sps_start_date,json=spsStartDate,proto3" json:"sps_start_date,omitempty"`
	Modality            string                 `protobuf:"bytes,8,opt,name=modality,proto3" json:"modality,omitempty"`
	RequestingPhysician string                 `protobuf:"bytes,9,opt,name=requesting_physician,json=requestingPhysician,proto3" json:"requesting_physician,omitempty"`
	ReferringPhysician  string                 `protobuf:"bytes,10,opt,name=referring_physician,json=referringPhysician,proto3" json:"referring_physician,omitempty"`
	PerformingPhysician string                 `protobuf:"bytes,11,opt,name=performing_physician,json=performingPhysician,proto3" json:"performing_physician,omitempty"`
	Status              string                 `protobuf:"bytes,12,opt,name=status,proto3" json:"status,omitempty"`
	Priority            string                 `protobuf:"bytes,13,opt,name=priority,proto3" json:"priority,omitempty"`
	ContrastAgent       string                 `protobuf:"bytes,14,opt,name=contrast_agent,json=contrastAgent,proto3" json:"contrast_agent,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *CreateWorklistEntry) Reset() {
	*x = CreateWorklistEntry{}
	mi := &file_pkg_proto_mws_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateWorklistEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateWorklistEntry) ProtoMessage() {}

func (x *CreateWorklistEntry) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_mws_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateWorklistEntry.ProtoReflect.Descriptor instead.
func (*CreateWorklistEntry) Descriptor() ([]byte, []int) {
	return file_pkg_proto_mws_proto_rawDescGZIP(), []int{0}
}

func (x *CreateWorklistEntry) GetPatientId() string {
	if x != nil {
		return x.PatientId
	}
	return ""
}

func (x *CreateWorklistEntry) GetPatientName() string {
	if x != nil {
		return x.PatientName
	}
	return ""
}

func (x *CreateWorklistEntry) GetPatientBirthDate() *timestamp.Timestamp {
	if x != nil {
		return x.PatientBirthDate
	}
	return nil
}

func (x *CreateWorklistEntry) GetPatientSex() string {
	if x != nil {
		return x.PatientSex
	}
	return ""
}

func (x *CreateWorklistEntry) GetStudyInstanceUid() string {
	if x != nil {
		return x.StudyInstanceUid
	}
	return ""
}

func (x *CreateWorklistEntry) GetSpsId() string {
	if x != nil {
		return x.SpsId
	}
	return ""
}

func (x *CreateWorklistEntry) GetSpsStartDate() *timestamp.Timestamp {
	if x != nil {
		return x.SpsStartDate
	}
	return nil
}

func (x *CreateWorklistEntry) GetModality() string {
	if x != nil {
		return x.Modality
	}
	return ""
}

func (x *CreateWorklistEntry) GetRequestingPhysician() string {
	if x != nil {
		return x.RequestingPhysician
	}
	return ""
}

func (x *CreateWorklistEntry) GetReferringPhysician() string {
	if x != nil {
		return x.ReferringPhysician
	}
	return ""
}

func (x *CreateWorklistEntry) GetPerformingPhysician() string {
	if x != nil {
		return x.PerformingPhysician
	}
	return ""
}

func (x *CreateWorklistEntry) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *CreateWorklistEntry) GetPriority() string {
	if x != nil {
		return x.Priority
	}
	return ""
}

func (x *CreateWorklistEntry) GetContrastAgent() string {
	if x != nil {
		return x.ContrastAgent
	}
	return ""
}

type CreateModality struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Modality       string                 `protobuf:"bytes,1,opt,name=modality,proto3" json:"modality,omitempty"`
	StationAeTitle string                 `protobuf:"bytes,2,opt,name=station_ae_title,json=stationAeTitle,proto3" json:"station_ae_title,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CreateModality) Reset() {
	*x = CreateModality{}
	mi := &file_pkg_proto_mws_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateModality) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateModality) ProtoMessage() {}

func (x *CreateModality) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_mws_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateModality.ProtoReflect.Descriptor instead.
func (*CreateModality) Descriptor() ([]byte, []int) {
	return file_pkg_proto_mws_proto_rawDescGZIP(), []int{1}
}

func (x *CreateModality) GetModality() string {
	if x != nil {
		return x.Modality
	}
	return ""
}

func (x *CreateModality) GetStationAeTitle() string {
	if x != nil {
		return x.StationAeTitle
	}
	return ""
}

type CreateStation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AeTitle       string                 `protobuf:"bytes,1,opt,name=ae_title,json=aeTitle,proto3" json:"ae_title,omitempty"`
	Hostname      string                 `protobuf:"bytes,2,opt,name=hostname,proto3" json:"hostname,omitempty"`
	Port          int32                  `protobuf:"varint,3,opt,name=port,proto3" json:"port,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Modality      string                 `protobuf:"bytes,5,opt,name=modality,proto3" json:"modality,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateStation) Reset() {
	*x = CreateStation{}
	mi := &file_pkg_proto_mws_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateStation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateStation) ProtoMessage() {}

func (x *CreateStation) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_mws_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateStation.ProtoReflect.Descriptor instead.
func (*CreateStation) Descriptor() ([]byte, []int) {
	return file_pkg_proto_mws_proto_rawDescGZIP(), []int{2}
}

func (x *CreateStation) GetAeTitle() string {
	if x != nil {
		return x.AeTitle
	}
	return ""
}

func (x *CreateStation) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *CreateStation) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *CreateStation) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateStation) GetModality() string {
	if x != nil {
		return x.Modality
	}
	return ""
}

var File_pkg_proto_mws_proto protoreflect.FileDescriptor

const file_pkg_proto_mws_proto_rawDesc = "" +
	"\n" +
	"\x13pkg/proto/mws.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xd7\x04\n" +
	"\x13CreateWorklistEntry\x12\x1d\n" +
	"\n" +
	"patient_id\x18\x01 \x01(\tR\tpatientId\x12!\n" +
	"\fpatient_name\x18\x02 \x01(\tR\vpatientName\x12H\n" +
	"\x12patient_birth_date\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\x10patientBirthDate\x12\x1f\n" +
	"\vpatient_sex\x18\x04 \x01(\tR\n" +
	"patientSex\x12,\n" +
	"\x12study_instance_uid\x18\x05 \x01(\tR\x10studyInstanceUid\x12\x15\n" +
	"\x06sps_id\x18\x06 \x01(\tR\x05spsId\x12@\n" +
	"\x0esps_start_date\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\fspsStartDate\x12\x1a\n" +
	"\bmodality\x18\b \x01(\tR\bmodality\x121\n" +
	"\x14requesting_physician\x18\t \x01(\tR\x13requestingPhysician\x12/\n" +
	"\x13referring_physician\x18\n" +
	" \x01(\tR\x12referringPhysician\x121\n" +
	"\x14performing_physician\x18\v \x01(\tR\x13performingPhysician\x12\x16\n" +
	"\x06status\x18\f \x01(\tR\x06status\x12\x1a\n" +
	"\bpriority\x18\r \x01(\tR\bpriority\x12%\n" +
	"\x0econtrast_agent\x18\x0e \x01(\tR\rcontrastAgent\"V\n" +
	"\x0eCreateModality\x12\x1a\n" +
	"\bmodality\x18\x01 \x01(\tR\bmodality\x12(\n" +
	"\x10station_ae_title\x18\x02 \x01(\tR\x0estationAeTitle\"\x98\x01\n" +
	"\rCreateStation\x12\x19\n" +
	"\bae_title\x18\x01 \x01(\tR\aaeTitle\x12\x1a\n" +
	"\bhostname\x18\x02 \x01(\tR\bhostname\x12\x12\n" +
	"\x04port\x18\x03 \x01(\x05R\x04port\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x1a\n" +
	"\bmodality\x18\x05 \x01(\tR\bmodalityB\x14Z\x12pkg/proto/worklistb\x06proto3"

var (
	file_pkg_proto_mws_proto_rawDescOnce sync.Once
	file_pkg_proto_mws_proto_rawDescData []byte
)

func file_pkg_proto_mws_proto_rawDescGZIP() []byte {
	file_pkg_proto_mws_proto_rawDescOnce.Do(func() {
		file_pkg_proto_mws_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_proto_mws_proto_rawDesc), len(file_pkg_proto_mws_proto_rawDesc)))
	})
	return file_pkg_proto_mws_proto_rawDescData
}

var file_pkg_proto_mws_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_pkg_proto_mws_proto_goTypes = []any{
	(*CreateWorklistEntry)(nil), // 0: CreateWorklistEntry
	(*CreateModality)(nil),      // 1: CreateModality
	(*CreateStation)(nil),       // 2: CreateStation
	(*timestamp.Timestamp)(nil), // 3: google.protobuf.Timestamp
}
var file_pkg_proto_mws_proto_depIdxs = []int32{
	3, // 0: CreateWorklistEntry.patient_birth_date:type_name -> google.protobuf.Timestamp
	3, // 1: CreateWorklistEntry.sps_start_date:type_name -> google.protobuf.Timestamp
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_pkg_proto_mws_proto_init() }
func file_pkg_proto_mws_proto_init() {
	if File_pkg_proto_mws_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_proto_mws_proto_rawDesc), len(file_pkg_proto_mws_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pkg_proto_mws_proto_goTypes,
		DependencyIndexes: file_pkg_proto_mws_proto_depIdxs,
		MessageInfos:      file_pkg_proto_mws_proto_msgTypes,
	}.Build()
	File_pkg_proto_mws_proto = out.File
	file_pkg_proto_mws_proto_goTypes = nil
	file_pkg_proto_mws_proto_depIdxs = nil
}
