// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.12.4
// source: pkg/proto/audit.proto

package audit

import (
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Audit struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Activity      string                 `protobuf:"bytes,2,opt,name=activity,proto3" json:"activity,omitempty"`
	User          string                 `protobuf:"bytes,3,opt,name=user,proto3" json:"user,omitempty"`
	Timestamp     *timestamp.Timestamp   `protobuf:"bytes,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Action        string                 `protobuf:"bytes,5,opt,name=action,proto3" json:"action,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Audit) Reset() {
	*x = Audit{}
	mi := &file_pkg_proto_audit_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Audit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Audit) ProtoMessage() {}

func (x *Audit) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_audit_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Audit.ProtoReflect.Descriptor instead.
func (*Audit) Descriptor() ([]byte, []int) {
	return file_pkg_proto_audit_proto_rawDescGZIP(), []int{0}
}

func (x *Audit) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Audit) GetActivity() string {
	if x != nil {
		return x.Activity
	}
	return ""
}

func (x *Audit) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

func (x *Audit) GetTimestamp() *timestamp.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *Audit) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

var File_pkg_proto_audit_proto protoreflect.FileDescriptor

const file_pkg_proto_audit_proto_rawDesc = "" +
	"\n" +
	"\x15pkg/proto/audit.proto\x12\x05proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\x99\x01\n" +
	"\x05Audit\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x1a\n" +
	"\bactivity\x18\x02 \x01(\tR\bactivity\x12\x12\n" +
	"\x04user\x18\x03 \x01(\tR\x04user\x128\n" +
	"\ttimestamp\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12\x16\n" +
	"\x06action\x18\x05 \x01(\tR\x06actionB\x11Z\x0fpkg/proto/auditb\x06proto3"

var (
	file_pkg_proto_audit_proto_rawDescOnce sync.Once
	file_pkg_proto_audit_proto_rawDescData []byte
)

func file_pkg_proto_audit_proto_rawDescGZIP() []byte {
	file_pkg_proto_audit_proto_rawDescOnce.Do(func() {
		file_pkg_proto_audit_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_proto_audit_proto_rawDesc), len(file_pkg_proto_audit_proto_rawDesc)))
	})
	return file_pkg_proto_audit_proto_rawDescData
}

var file_pkg_proto_audit_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_pkg_proto_audit_proto_goTypes = []any{
	(*Audit)(nil),               // 0: proto.Audit
	(*timestamp.Timestamp)(nil), // 1: google.protobuf.Timestamp
}
var file_pkg_proto_audit_proto_depIdxs = []int32{
	1, // 0: proto.Audit.timestamp:type_name -> google.protobuf.Timestamp
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_pkg_proto_audit_proto_init() }
func file_pkg_proto_audit_proto_init() {
	if File_pkg_proto_audit_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_proto_audit_proto_rawDesc), len(file_pkg_proto_audit_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pkg_proto_audit_proto_goTypes,
		DependencyIndexes: file_pkg_proto_audit_proto_depIdxs,
		MessageInfos:      file_pkg_proto_audit_proto_msgTypes,
	}.Build()
	File_pkg_proto_audit_proto = out.File
	file_pkg_proto_audit_proto_goTypes = nil
	file_pkg_proto_audit_proto_depIdxs = nil
}
