// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.12.4
// source: pkg/proto/gateway.proto

package gateway

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type VerifyStudyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StudyUid      string                 `protobuf:"bytes,1,opt,name=study_uid,json=studyUid,proto3" json:"study_uid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyStudyRequest) Reset() {
	*x = VerifyStudyRequest{}
	mi := &file_pkg_proto_gateway_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyStudyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyStudyRequest) ProtoMessage() {}

func (x *VerifyStudyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_gateway_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyStudyRequest.ProtoReflect.Descriptor instead.
func (*VerifyStudyRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_gateway_proto_rawDescGZIP(), []int{0}
}

func (x *VerifyStudyRequest) GetStudyUid() string {
	if x != nil {
		return x.StudyUid
	}
	return ""
}

type VerifyStudyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Exists        bool                   `protobuf:"varint,1,opt,name=exists,proto3" json:"exists,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	StudyUid      string                 `protobuf:"bytes,3,opt,name=study_uid,json=studyUid,proto3" json:"study_uid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyStudyResponse) Reset() {
	*x = VerifyStudyResponse{}
	mi := &file_pkg_proto_gateway_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyStudyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyStudyResponse) ProtoMessage() {}

func (x *VerifyStudyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_gateway_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyStudyResponse.ProtoReflect.Descriptor instead.
func (*VerifyStudyResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_gateway_proto_rawDescGZIP(), []int{1}
}

func (x *VerifyStudyResponse) GetExists() bool {
	if x != nil {
		return x.Exists
	}
	return false
}

func (x *VerifyStudyResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *VerifyStudyResponse) GetStudyUid() string {
	if x != nil {
		return x.StudyUid
	}
	return ""
}

var File_pkg_proto_gateway_proto protoreflect.FileDescriptor

const file_pkg_proto_gateway_proto_rawDesc = "" +
	"\n" +
	"\x17pkg/proto/gateway.proto\x12\x05proto\"1\n" +
	"\x12VerifyStudyRequest\x12\x1b\n" +
	"\tstudy_uid\x18\x01 \x01(\tR\bstudyUid\"d\n" +
	"\x13VerifyStudyResponse\x12\x16\n" +
	"\x06exists\x18\x01 \x01(\bR\x06exists\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1b\n" +
	"\tstudy_uid\x18\x03 \x01(\tR\bstudyUid2T\n" +
	"\fStudyService\x12D\n" +
	"\vVerifyStudy\x12\x19.proto.VerifyStudyRequest\x1a\x1a.proto.VerifyStudyResponseB\x13Z\x11pkg/proto/gatewayb\x06proto3"

var (
	file_pkg_proto_gateway_proto_rawDescOnce sync.Once
	file_pkg_proto_gateway_proto_rawDescData []byte
)

func file_pkg_proto_gateway_proto_rawDescGZIP() []byte {
	file_pkg_proto_gateway_proto_rawDescOnce.Do(func() {
		file_pkg_proto_gateway_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_proto_gateway_proto_rawDesc), len(file_pkg_proto_gateway_proto_rawDesc)))
	})
	return file_pkg_proto_gateway_proto_rawDescData
}

var file_pkg_proto_gateway_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_pkg_proto_gateway_proto_goTypes = []any{
	(*VerifyStudyRequest)(nil),  // 0: proto.VerifyStudyRequest
	(*VerifyStudyResponse)(nil), // 1: proto.VerifyStudyResponse
}
var file_pkg_proto_gateway_proto_depIdxs = []int32{
	0, // 0: proto.StudyService.VerifyStudy:input_type -> proto.VerifyStudyRequest
	1, // 1: proto.StudyService.VerifyStudy:output_type -> proto.VerifyStudyResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pkg_proto_gateway_proto_init() }
func file_pkg_proto_gateway_proto_init() {
	if File_pkg_proto_gateway_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_proto_gateway_proto_rawDesc), len(file_pkg_proto_gateway_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_proto_gateway_proto_goTypes,
		DependencyIndexes: file_pkg_proto_gateway_proto_depIdxs,
		MessageInfos:      file_pkg_proto_gateway_proto_msgTypes,
	}.Build()
	File_pkg_proto_gateway_proto = out.File
	file_pkg_proto_gateway_proto_goTypes = nil
	file_pkg_proto_gateway_proto_depIdxs = nil
}
