// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: pkg/proto/lab.proto

package lab

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// A lab order, as finance needs to see it.
//
// This is a billing projection, not the order. The lab owns the order and everything
// clinical about it; finance is told only what it needs to raise a charge and take payment.
// Results, specimens and reference ranges are deliberately absent — finance has no business
// holding a patient's creatinine, and a projection that carries it becomes a second copy of
// the record that nobody remembers to keep in step.
type LabOrderLine struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Id    uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// Exactly one of these is set. A panel bills as one line at the panel's own price, which
	// is normally less than its members would come to individually.
	TestId  uint32 `protobuf:"varint,2,opt,name=test_id,json=testId,proto3" json:"test_id,omitempty"`
	PanelId uint32 `protobuf:"varint,3,opt,name=panel_id,json=panelId,proto3" json:"panel_id,omitempty"`
	// Code and name are copied rather than referenced, so a receipt reprinted next year says
	// what was actually charged for. Renaming a test in the catalogue must not rewrite
	// history on a document somebody has already paid against.
	Code          string  `protobuf:"bytes,4,opt,name=code,proto3" json:"code,omitempty"`
	Name          string  `protobuf:"bytes,5,opt,name=name,proto3" json:"name,omitempty"`
	Price         float64 `protobuf:"fixed64,6,opt,name=price,proto3" json:"price,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LabOrderLine) Reset() {
	*x = LabOrderLine{}
	mi := &file_pkg_proto_lab_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LabOrderLine) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LabOrderLine) ProtoMessage() {}

func (x *LabOrderLine) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_lab_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LabOrderLine.ProtoReflect.Descriptor instead.
func (*LabOrderLine) Descriptor() ([]byte, []int) {
	return file_pkg_proto_lab_proto_rawDescGZIP(), []int{0}
}

func (x *LabOrderLine) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *LabOrderLine) GetTestId() uint32 {
	if x != nil {
		return x.TestId
	}
	return 0
}

func (x *LabOrderLine) GetPanelId() uint32 {
	if x != nil {
		return x.PanelId
	}
	return 0
}

func (x *LabOrderLine) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *LabOrderLine) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *LabOrderLine) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

type LabOrder struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	Id          uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	OrderNumber string                 `protobuf:"bytes,2,opt,name=order_number,json=orderNumber,proto3" json:"order_number,omitempty"`
	PatientId   uint32                 `protobuf:"varint,3,opt,name=patient_id,json=patientId,proto3" json:"patient_id,omitempty"`
	Lines       []*LabOrderLine        `protobuf:"bytes,4,rep,name=lines,proto3" json:"lines,omitempty"`
	TotalPrice  float64                `protobuf:"fixed64,5,opt,name=total_price,json=totalPrice,proto3" json:"total_price,omitempty"`
	// Priority decides whether the collection gate can be walked past. STAT and urgent work
	// is drawn before payment and flagged for finance to chase, so a cashier seeing an
	// unpaid STAT order is looking at something already in progress, not something to hold.
	Priority string `protobuf:"bytes,6,opt,name=priority,proto3" json:"priority,omitempty"`
	// Who settles. An order against an organization, a referring centre or an insurer is
	// invoiced monthly and must never appear on a counter's list of outstanding payments;
	// one against a walk-in patient must.
	OrganizationId    uint32 `protobuf:"varint,7,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	ReferringCenterId uint32 `protobuf:"varint,8,opt,name=referring_center_id,json=referringCenterId,proto3" json:"referring_center_id,omitempty"`
	InsuranceId       uint32 `protobuf:"varint,9,opt,name=insurance_id,json=insuranceId,proto3" json:"insurance_id,omitempty"`
	CenterId          uint32 `protobuf:"varint,10,opt,name=center_id,json=centerId,proto3" json:"center_id,omitempty"`
	OrderedBy         uint32 `protobuf:"varint,11,opt,name=ordered_by,json=orderedBy,proto3" json:"ordered_by,omitempty"`
	OrderedAt         string `protobuf:"bytes,12,opt,name=ordered_at,json=orderedAt,proto3" json:"ordered_at,omitempty"`
	// Status carries cancellations. A cancelled order that was never collected should stop
	// being billable, and one already drawn should not.
	Status        string `protobuf:"bytes,13,opt,name=status,proto3" json:"status,omitempty"`
	IsActive      bool   `protobuf:"varint,14,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LabOrder) Reset() {
	*x = LabOrder{}
	mi := &file_pkg_proto_lab_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LabOrder) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LabOrder) ProtoMessage() {}

func (x *LabOrder) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_lab_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LabOrder.ProtoReflect.Descriptor instead.
func (*LabOrder) Descriptor() ([]byte, []int) {
	return file_pkg_proto_lab_proto_rawDescGZIP(), []int{1}
}

func (x *LabOrder) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *LabOrder) GetOrderNumber() string {
	if x != nil {
		return x.OrderNumber
	}
	return ""
}

func (x *LabOrder) GetPatientId() uint32 {
	if x != nil {
		return x.PatientId
	}
	return 0
}

func (x *LabOrder) GetLines() []*LabOrderLine {
	if x != nil {
		return x.Lines
	}
	return nil
}

func (x *LabOrder) GetTotalPrice() float64 {
	if x != nil {
		return x.TotalPrice
	}
	return 0
}

func (x *LabOrder) GetPriority() string {
	if x != nil {
		return x.Priority
	}
	return ""
}

func (x *LabOrder) GetOrganizationId() uint32 {
	if x != nil {
		return x.OrganizationId
	}
	return 0
}

func (x *LabOrder) GetReferringCenterId() uint32 {
	if x != nil {
		return x.ReferringCenterId
	}
	return 0
}

func (x *LabOrder) GetInsuranceId() uint32 {
	if x != nil {
		return x.InsuranceId
	}
	return 0
}

func (x *LabOrder) GetCenterId() uint32 {
	if x != nil {
		return x.CenterId
	}
	return 0
}

func (x *LabOrder) GetOrderedBy() uint32 {
	if x != nil {
		return x.OrderedBy
	}
	return 0
}

func (x *LabOrder) GetOrderedAt() string {
	if x != nil {
		return x.OrderedAt
	}
	return ""
}

func (x *LabOrder) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *LabOrder) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

var File_pkg_proto_lab_proto protoreflect.FileDescriptor

const file_pkg_proto_lab_proto_rawDesc = "" +
	"\n" +
	"\x13pkg/proto/lab.proto\x12\x03lab\"\x90\x01\n" +
	"\fLabOrderLine\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x17\n" +
	"\atest_id\x18\x02 \x01(\rR\x06testId\x12\x19\n" +
	"\bpanel_id\x18\x03 \x01(\rR\apanelId\x12\x12\n" +
	"\x04code\x18\x04 \x01(\tR\x04code\x12\x12\n" +
	"\x04name\x18\x05 \x01(\tR\x04name\x12\x14\n" +
	"\x05price\x18\x06 \x01(\x01R\x05price\"\xce\x03\n" +
	"\bLabOrder\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12!\n" +
	"\forder_number\x18\x02 \x01(\tR\vorderNumber\x12\x1d\n" +
	"\n" +
	"patient_id\x18\x03 \x01(\rR\tpatientId\x12'\n" +
	"\x05lines\x18\x04 \x03(\v2\x11.lab.LabOrderLineR\x05lines\x12\x1f\n" +
	"\vtotal_price\x18\x05 \x01(\x01R\n" +
	"totalPrice\x12\x1a\n" +
	"\bpriority\x18\x06 \x01(\tR\bpriority\x12'\n" +
	"\x0forganization_id\x18\a \x01(\rR\x0eorganizationId\x12.\n" +
	"\x13referring_center_id\x18\b \x01(\rR\x11referringCenterId\x12!\n" +
	"\finsurance_id\x18\t \x01(\rR\vinsuranceId\x12\x1b\n" +
	"\tcenter_id\x18\n" +
	" \x01(\rR\bcenterId\x12\x1d\n" +
	"\n" +
	"ordered_by\x18\v \x01(\rR\torderedBy\x12\x1d\n" +
	"\n" +
	"ordered_at\x18\f \x01(\tR\torderedAt\x12\x16\n" +
	"\x06status\x18\r \x01(\tR\x06status\x12\x1b\n" +
	"\tis_active\x18\x0e \x01(\bR\bisActiveB\x0fZ\rpkg/proto/labb\x06proto3"

var (
	file_pkg_proto_lab_proto_rawDescOnce sync.Once
	file_pkg_proto_lab_proto_rawDescData []byte
)

func file_pkg_proto_lab_proto_rawDescGZIP() []byte {
	file_pkg_proto_lab_proto_rawDescOnce.Do(func() {
		file_pkg_proto_lab_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_proto_lab_proto_rawDesc), len(file_pkg_proto_lab_proto_rawDesc)))
	})
	return file_pkg_proto_lab_proto_rawDescData
}

var file_pkg_proto_lab_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_pkg_proto_lab_proto_goTypes = []any{
	(*LabOrderLine)(nil), // 0: lab.LabOrderLine
	(*LabOrder)(nil),     // 1: lab.LabOrder
}
var file_pkg_proto_lab_proto_depIdxs = []int32{
	0, // 0: lab.LabOrder.lines:type_name -> lab.LabOrderLine
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_pkg_proto_lab_proto_init() }
func file_pkg_proto_lab_proto_init() {
	if File_pkg_proto_lab_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_proto_lab_proto_rawDesc), len(file_pkg_proto_lab_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pkg_proto_lab_proto_goTypes,
		DependencyIndexes: file_pkg_proto_lab_proto_depIdxs,
		MessageInfos:      file_pkg_proto_lab_proto_msgTypes,
	}.Build()
	File_pkg_proto_lab_proto = out.File
	file_pkg_proto_lab_proto_goTypes = nil
	file_pkg_proto_lab_proto_depIdxs = nil
}
