// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.12.4
// source: pkg/proto/wallet.proto

package wallet

import (
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Wallet struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`                               // Use int32 for ID
	Amount        float64                `protobuf:"fixed64,2,opt,name=amount,proto3" json:"amount,omitempty"`                      // Amount (float64)
	DoctorId      int32                  `protobuf:"varint,3,opt,name=doctor_id,json=doctorId,proto3" json:"doctor_id,omitempty"`   // Doctor ID
	CreatedAt     *timestamp.Timestamp   `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"` // Created timestamp
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Wallet) Reset() {
	*x = Wallet{}
	mi := &file_pkg_proto_wallet_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Wallet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Wallet) ProtoMessage() {}

func (x *Wallet) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_wallet_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Wallet.ProtoReflect.Descriptor instead.
func (*Wallet) Descriptor() ([]byte, []int) {
	return file_pkg_proto_wallet_proto_rawDescGZIP(), []int{0}
}

func (x *Wallet) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Wallet) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *Wallet) GetDoctorId() int32 {
	if x != nil {
		return x.DoctorId
	}
	return 0
}

func (x *Wallet) GetCreatedAt() *timestamp.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type GetWalletRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DoctorId      int32                  `protobuf:"varint,1,opt,name=doctor_id,json=doctorId,proto3" json:"doctor_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWalletRequest) Reset() {
	*x = GetWalletRequest{}
	mi := &file_pkg_proto_wallet_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWalletRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWalletRequest) ProtoMessage() {}

func (x *GetWalletRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_wallet_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWalletRequest.ProtoReflect.Descriptor instead.
func (*GetWalletRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_wallet_proto_rawDescGZIP(), []int{1}
}

func (x *GetWalletRequest) GetDoctorId() int32 {
	if x != nil {
		return x.DoctorId
	}
	return 0
}

var File_pkg_proto_wallet_proto protoreflect.FileDescriptor

const file_pkg_proto_wallet_proto_rawDesc = "" +
	"\n" +
	"\x16pkg/proto/wallet.proto\x12\x05proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\x88\x01\n" +
	"\x06Wallet\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\x01R\x06amount\x12\x1b\n" +
	"\tdoctor_id\x18\x03 \x01(\x05R\bdoctorId\x129\n" +
	"\n" +
	"created_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"/\n" +
	"\x10GetWalletRequest\x12\x1b\n" +
	"\tdoctor_id\x18\x01 \x01(\x05R\bdoctorId2G\n" +
	"\x0eFinanceService\x125\n" +
	"\tGetWallet\x12\x17.proto.GetWalletRequest\x1a\r.proto.Wallet\"\x00B\x12Z\x10pkg/proto/walletb\x06proto3"

var (
	file_pkg_proto_wallet_proto_rawDescOnce sync.Once
	file_pkg_proto_wallet_proto_rawDescData []byte
)

func file_pkg_proto_wallet_proto_rawDescGZIP() []byte {
	file_pkg_proto_wallet_proto_rawDescOnce.Do(func() {
		file_pkg_proto_wallet_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_proto_wallet_proto_rawDesc), len(file_pkg_proto_wallet_proto_rawDesc)))
	})
	return file_pkg_proto_wallet_proto_rawDescData
}

var file_pkg_proto_wallet_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_pkg_proto_wallet_proto_goTypes = []any{
	(*Wallet)(nil),              // 0: proto.Wallet
	(*GetWalletRequest)(nil),    // 1: proto.GetWalletRequest
	(*timestamp.Timestamp)(nil), // 2: google.protobuf.Timestamp
}
var file_pkg_proto_wallet_proto_depIdxs = []int32{
	2, // 0: proto.Wallet.created_at:type_name -> google.protobuf.Timestamp
	1, // 1: proto.FinanceService.GetWallet:input_type -> proto.GetWalletRequest
	0, // 2: proto.FinanceService.GetWallet:output_type -> proto.Wallet
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_pkg_proto_wallet_proto_init() }
func file_pkg_proto_wallet_proto_init() {
	if File_pkg_proto_wallet_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_proto_wallet_proto_rawDesc), len(file_pkg_proto_wallet_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_proto_wallet_proto_goTypes,
		DependencyIndexes: file_pkg_proto_wallet_proto_depIdxs,
		MessageInfos:      file_pkg_proto_wallet_proto_msgTypes,
	}.Build()
	File_pkg_proto_wallet_proto = out.File
	file_pkg_proto_wallet_proto_goTypes = nil
	file_pkg_proto_wallet_proto_depIdxs = nil
}
