// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.12.4
// source: pkg/proto/facility.proto

package facility

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Modality struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	Id                     uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                   string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	ShortName              string                 `protobuf:"bytes,3,opt,name=shortName,proto3" json:"shortName,omitempty"`
	EstimatedReportingTime uint32                 `protobuf:"varint,4,opt,name=estimatedReportingTime,proto3" json:"estimatedReportingTime,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *Modality) Reset() {
	*x = Modality{}
	mi := &file_pkg_proto_facility_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Modality) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Modality) ProtoMessage() {}

func (x *Modality) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_facility_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Modality.ProtoReflect.Descriptor instead.
func (*Modality) Descriptor() ([]byte, []int) {
	return file_pkg_proto_facility_proto_rawDescGZIP(), []int{0}
}

func (x *Modality) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Modality) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Modality) GetShortName() string {
	if x != nil {
		return x.ShortName
	}
	return ""
}

func (x *Modality) GetEstimatedReportingTime() uint32 {
	if x != nil {
		return x.EstimatedReportingTime
	}
	return 0
}

type Procedure struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	ModalityId    uint32                 `protobuf:"varint,3,opt,name=modalityId,proto3" json:"modalityId,omitempty"`
	Price         float64                `protobuf:"fixed64,4,opt,name=price,proto3" json:"price,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Procedure) Reset() {
	*x = Procedure{}
	mi := &file_pkg_proto_facility_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Procedure) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Procedure) ProtoMessage() {}

func (x *Procedure) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_facility_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Procedure.ProtoReflect.Descriptor instead.
func (*Procedure) Descriptor() ([]byte, []int) {
	return file_pkg_proto_facility_proto_rawDescGZIP(), []int{1}
}

func (x *Procedure) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Procedure) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Procedure) GetModalityId() uint32 {
	if x != nil {
		return x.ModalityId
	}
	return 0
}

func (x *Procedure) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

var File_pkg_proto_facility_proto protoreflect.FileDescriptor

const file_pkg_proto_facility_proto_rawDesc = "" +
	"\n" +
	"\x18pkg/proto/facility.proto\x12\x05proto\"\x84\x01\n" +
	"\bModality\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1c\n" +
	"\tshortName\x18\x03 \x01(\tR\tshortName\x126\n" +
	"\x16estimatedReportingTime\x18\x04 \x01(\rR\x16estimatedReportingTime\"e\n" +
	"\tProcedure\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1e\n" +
	"\n" +
	"modalityId\x18\x03 \x01(\rR\n" +
	"modalityId\x12\x14\n" +
	"\x05price\x18\x04 \x01(\x01R\x05priceB\x14Z\x12pkg/proto/facilityb\x06proto3"

var (
	file_pkg_proto_facility_proto_rawDescOnce sync.Once
	file_pkg_proto_facility_proto_rawDescData []byte
)

func file_pkg_proto_facility_proto_rawDescGZIP() []byte {
	file_pkg_proto_facility_proto_rawDescOnce.Do(func() {
		file_pkg_proto_facility_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_proto_facility_proto_rawDesc), len(file_pkg_proto_facility_proto_rawDesc)))
	})
	return file_pkg_proto_facility_proto_rawDescData
}

var file_pkg_proto_facility_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_pkg_proto_facility_proto_goTypes = []any{
	(*Modality)(nil),  // 0: proto.Modality
	(*Procedure)(nil), // 1: proto.Procedure
}
var file_pkg_proto_facility_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pkg_proto_facility_proto_init() }
func file_pkg_proto_facility_proto_init() {
	if File_pkg_proto_facility_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_proto_facility_proto_rawDesc), len(file_pkg_proto_facility_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pkg_proto_facility_proto_goTypes,
		DependencyIndexes: file_pkg_proto_facility_proto_depIdxs,
		MessageInfos:      file_pkg_proto_facility_proto_msgTypes,
	}.Build()
	File_pkg_proto_facility_proto = out.File
	file_pkg_proto_facility_proto_goTypes = nil
	file_pkg_proto_facility_proto_depIdxs = nil
}
