# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: pkg/proto/mws.proto
# Protobuf Python Version: 5.29.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    3,
    '',
    'pkg/proto/mws.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13pkg/proto/mws.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xab\x03\n\x13\x43reateWorklistEntry\x12\x12\n\npatient_id\x18\x01 \x01(\t\x12\x14\n\x0cpatient_name\x18\x02 \x01(\t\x12\x36\n\x12patient_birth_date\x18\x03 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x13\n\x0bpatient_sex\x18\x04 \x01(\t\x12\x1a\n\x12study_instance_uid\x18\x05 \x01(\t\x12\x0e\n\x06sps_id\x18\x06 \x01(\t\x12\x32\n\x0esps_start_date\x18\x07 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x10\n\x08modality\x18\x08 \x01(\t\x12\x1c\n\x14requesting_physician\x18\t \x01(\t\x12\x1b\n\x13referring_physician\x18\n \x01(\t\x12\x1c\n\x14performing_physician\x18\x0b \x01(\t\x12\x0e\n\x06status\x18\x0c \x01(\t\x12\x10\n\x08priority\x18\r \x01(\t\x12\x16\n\x0e\x63ontrast_agent\x18\x0e \x01(\t\x12\x18\n\x10\x61\x63\x63\x65ssion_number\x18\x0f \x01(\t\"Q\n\x0e\x43reateModality\x12\x10\n\x08modality\x18\x01 \x01(\t\x12\x18\n\x10station_ae_title\x18\x02 \x01(\t\x12\x13\n\x0bmodality_id\x18\x03 \x01(\x05\"|\n\rCreateStation\x12\x10\n\x08\x61\x65_title\x18\x01 \x01(\t\x12\x10\n\x08hostname\x18\x02 \x01(\t\x12\x0c\n\x04port\x18\x03 \x01(\x05\x12\x13\n\x0b\x64\x65scription\x18\x04 \x01(\t\x12\x10\n\x08modality\x18\x05 \x01(\t\x12\x12\n\nstation_id\x18\x06 \x01(\x05\x42\x14Z\x12pkg/proto/worklistb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'pkg.proto.mws_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\022pkg/proto/worklist'
  _globals['_CREATEWORKLISTENTRY']._serialized_start=57
  _globals['_CREATEWORKLISTENTRY']._serialized_end=484
  _globals['_CREATEMODALITY']._serialized_start=486
  _globals['_CREATEMODALITY']._serialized_end=567
  _globals['_CREATESTATION']._serialized_start=569
  _globals['_CREATESTATION']._serialized_end=693
# @@protoc_insertion_point(module_scope)
