// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.12.4
// source: appointment.proto

package appointment

import (
	patient "github.com/OtchereDev/ris-common-sdk/pkg/proto/patient"
	referral "github.com/OtchereDev/ris-common-sdk/pkg/proto/referral"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Appointment struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	Id                    uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	PatientId             uint32                 `protobuf:"varint,2,opt,name=patient_id,json=patientId,proto3" json:"patient_id,omitempty"`
	IsEmergency           bool                   `protobuf:"varint,3,opt,name=is_emergency,json=isEmergency,proto3" json:"is_emergency,omitempty"`
	ProcedureId           uint32                 `protobuf:"varint,4,opt,name=procedure_id,json=procedureId,proto3" json:"procedure_id,omitempty"`
	ReportId              uint32                 `protobuf:"varint,5,opt,name=report_id,json=reportId,proto3" json:"report_id,omitempty"`
	ReferringDoctorId     uint32                 `protobuf:"varint,6,opt,name=referring_doctor_id,json=referringDoctorId,proto3" json:"referring_doctor_id,omitempty"`
	ReportingDoctorId     uint32                 `protobuf:"varint,7,opt,name=reporting_doctor_id,json=reportingDoctorId,proto3" json:"reporting_doctor_id,omitempty"`
	AppointmentTime       *timestamp.Timestamp   `protobuf:"bytes,8,opt,name=appointment_time,json=appointmentTime,proto3" json:"appointment_time,omitempty"`
	OrganizationId        uint32                 `protobuf:"varint,9,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	PaymentId             uint32                 `protobuf:"varint,10,opt,name=payment_id,json=paymentId,proto3" json:"payment_id,omitempty"`
	Note                  string                 `protobuf:"bytes,11,opt,name=note,proto3" json:"note,omitempty"`
	Status                string                 `protobuf:"bytes,12,opt,name=status,proto3" json:"status,omitempty"`
	RequestForm           []*RequestForm         `protobuf:"bytes,13,rep,name=request_form,json=requestForm,proto3" json:"request_form,omitempty"`
	HasPaidCommission     bool                   `protobuf:"varint,14,opt,name=has_paid_commission,json=hasPaidCommission,proto3" json:"has_paid_commission,omitempty"`
	CreatedAt             *timestamp.Timestamp   `protobuf:"bytes,15,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	OriginalAppointmentId uint32                 `protobuf:"varint,16,opt,name=original_appointment_id,json=originalAppointmentId,proto3" json:"original_appointment_id,omitempty"`
	ParentAppointmentId   uint32                 `protobuf:"varint,17,opt,name=parent_appointment_id,json=parentAppointmentId,proto3" json:"parent_appointment_id,omitempty"`
	Version               int32                  `protobuf:"varint,18,opt,name=version,proto3" json:"version,omitempty"`
	IsActive              bool                   `protobuf:"varint,19,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	IsOriginal            bool                   `protobuf:"varint,20,opt,name=is_original,json=isOriginal,proto3" json:"is_original,omitempty"`
	ModifiedBy            uint32                 `protobuf:"varint,22,opt,name=modified_by,json=modifiedBy,proto3" json:"modified_by,omitempty"`
	ModificationReason    string                 `protobuf:"bytes,23,opt,name=modification_reason,json=modificationReason,proto3" json:"modification_reason,omitempty"`
	ModifiedAt            *timestamp.Timestamp   `protobuf:"bytes,24,opt,name=modified_at,json=modifiedAt,proto3" json:"modified_at,omitempty"`
	IsLocked              bool                   `protobuf:"varint,25,opt,name=is_locked,json=isLocked,proto3" json:"is_locked,omitempty"`
	ReasonForLocking      string                 `protobuf:"bytes,26,opt,name=reason_for_locking,json=reasonForLocking,proto3" json:"reason_for_locking,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *Appointment) Reset() {
	*x = Appointment{}
	mi := &file_appointment_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Appointment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Appointment) ProtoMessage() {}

func (x *Appointment) ProtoReflect() protoreflect.Message {
	mi := &file_appointment_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Appointment.ProtoReflect.Descriptor instead.
func (*Appointment) Descriptor() ([]byte, []int) {
	return file_appointment_proto_rawDescGZIP(), []int{0}
}

func (x *Appointment) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Appointment) GetPatientId() uint32 {
	if x != nil {
		return x.PatientId
	}
	return 0
}

func (x *Appointment) GetIsEmergency() bool {
	if x != nil {
		return x.IsEmergency
	}
	return false
}

func (x *Appointment) GetProcedureId() uint32 {
	if x != nil {
		return x.ProcedureId
	}
	return 0
}

func (x *Appointment) GetReportId() uint32 {
	if x != nil {
		return x.ReportId
	}
	return 0
}

func (x *Appointment) GetReferringDoctorId() uint32 {
	if x != nil {
		return x.ReferringDoctorId
	}
	return 0
}

func (x *Appointment) GetReportingDoctorId() uint32 {
	if x != nil {
		return x.ReportingDoctorId
	}
	return 0
}

func (x *Appointment) GetAppointmentTime() *timestamp.Timestamp {
	if x != nil {
		return x.AppointmentTime
	}
	return nil
}

func (x *Appointment) GetOrganizationId() uint32 {
	if x != nil {
		return x.OrganizationId
	}
	return 0
}

func (x *Appointment) GetPaymentId() uint32 {
	if x != nil {
		return x.PaymentId
	}
	return 0
}

func (x *Appointment) GetNote() string {
	if x != nil {
		return x.Note
	}
	return ""
}

func (x *Appointment) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Appointment) GetRequestForm() []*RequestForm {
	if x != nil {
		return x.RequestForm
	}
	return nil
}

func (x *Appointment) GetHasPaidCommission() bool {
	if x != nil {
		return x.HasPaidCommission
	}
	return false
}

func (x *Appointment) GetCreatedAt() *timestamp.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Appointment) GetOriginalAppointmentId() uint32 {
	if x != nil {
		return x.OriginalAppointmentId
	}
	return 0
}

func (x *Appointment) GetParentAppointmentId() uint32 {
	if x != nil {
		return x.ParentAppointmentId
	}
	return 0
}

func (x *Appointment) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *Appointment) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

func (x *Appointment) GetIsOriginal() bool {
	if x != nil {
		return x.IsOriginal
	}
	return false
}

func (x *Appointment) GetModifiedBy() uint32 {
	if x != nil {
		return x.ModifiedBy
	}
	return 0
}

func (x *Appointment) GetModificationReason() string {
	if x != nil {
		return x.ModificationReason
	}
	return ""
}

func (x *Appointment) GetModifiedAt() *timestamp.Timestamp {
	if x != nil {
		return x.ModifiedAt
	}
	return nil
}

func (x *Appointment) GetIsLocked() bool {
	if x != nil {
		return x.IsLocked
	}
	return false
}

func (x *Appointment) GetReasonForLocking() string {
	if x != nil {
		return x.ReasonForLocking
	}
	return ""
}

type ReportVersion struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	ReportId        uint32                 `protobuf:"varint,2,opt,name=report_id,json=reportId,proto3" json:"report_id,omitempty"`
	RadiologistId   uint32                 `protobuf:"varint,3,opt,name=radiologist_id,json=radiologistId,proto3" json:"radiologist_id,omitempty"`
	Findings        string                 `protobuf:"bytes,4,opt,name=findings,proto3" json:"findings,omitempty"`
	Impressions     string                 `protobuf:"bytes,5,opt,name=impressions,proto3" json:"impressions,omitempty"`
	ClinicalDetails string                 `protobuf:"bytes,6,opt,name=clinical_details,json=clinicalDetails,proto3" json:"clinical_details,omitempty"`
	Url             string                 `protobuf:"bytes,7,opt,name=url,proto3" json:"url,omitempty"`
	Status          string                 `protobuf:"bytes,8,opt,name=status,proto3" json:"status,omitempty"`
	NoHeaderUrl     string                 `protobuf:"bytes,9,opt,name=no_header_url,json=noHeaderUrl,proto3" json:"no_header_url,omitempty"`
	ConfirmedAt     *timestamp.Timestamp   `protobuf:"bytes,10,opt,name=confirmed_at,json=confirmedAt,proto3" json:"confirmed_at,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ReportVersion) Reset() {
	*x = ReportVersion{}
	mi := &file_appointment_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportVersion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportVersion) ProtoMessage() {}

func (x *ReportVersion) ProtoReflect() protoreflect.Message {
	mi := &file_appointment_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportVersion.ProtoReflect.Descriptor instead.
func (*ReportVersion) Descriptor() ([]byte, []int) {
	return file_appointment_proto_rawDescGZIP(), []int{1}
}

func (x *ReportVersion) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ReportVersion) GetReportId() uint32 {
	if x != nil {
		return x.ReportId
	}
	return 0
}

func (x *ReportVersion) GetRadiologistId() uint32 {
	if x != nil {
		return x.RadiologistId
	}
	return 0
}

func (x *ReportVersion) GetFindings() string {
	if x != nil {
		return x.Findings
	}
	return ""
}

func (x *ReportVersion) GetImpressions() string {
	if x != nil {
		return x.Impressions
	}
	return ""
}

func (x *ReportVersion) GetClinicalDetails() string {
	if x != nil {
		return x.ClinicalDetails
	}
	return ""
}

func (x *ReportVersion) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *ReportVersion) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ReportVersion) GetNoHeaderUrl() string {
	if x != nil {
		return x.NoHeaderUrl
	}
	return ""
}

func (x *ReportVersion) GetConfirmedAt() *timestamp.Timestamp {
	if x != nil {
		return x.ConfirmedAt
	}
	return nil
}

type Report struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Id                uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	AppointmentId     uint32                 `protobuf:"varint,2,opt,name=appointment_id,json=appointmentId,proto3" json:"appointment_id,omitempty"`
	ReferringHospital string                 `protobuf:"bytes,3,opt,name=referring_hospital,json=referringHospital,proto3" json:"referring_hospital,omitempty"`
	IsCompleted       bool                   `protobuf:"varint,4,opt,name=is_completed,json=isCompleted,proto3" json:"is_completed,omitempty"`
	Versions          []*ReportVersion       `protobuf:"bytes,5,rep,name=versions,proto3" json:"versions,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *Report) Reset() {
	*x = Report{}
	mi := &file_appointment_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Report) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Report) ProtoMessage() {}

func (x *Report) ProtoReflect() protoreflect.Message {
	mi := &file_appointment_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Report.ProtoReflect.Descriptor instead.
func (*Report) Descriptor() ([]byte, []int) {
	return file_appointment_proto_rawDescGZIP(), []int{2}
}

func (x *Report) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Report) GetAppointmentId() uint32 {
	if x != nil {
		return x.AppointmentId
	}
	return 0
}

func (x *Report) GetReferringHospital() string {
	if x != nil {
		return x.ReferringHospital
	}
	return ""
}

func (x *Report) GetIsCompleted() bool {
	if x != nil {
		return x.IsCompleted
	}
	return false
}

func (x *Report) GetVersions() []*ReportVersion {
	if x != nil {
		return x.Versions
	}
	return nil
}

type RequestForm struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	AppointmentId uint32                 `protobuf:"varint,2,opt,name=appointment_id,json=appointmentId,proto3" json:"appointment_id,omitempty"`
	Url           string                 `protobuf:"bytes,3,opt,name=url,proto3" json:"url,omitempty"`
	IsFile        bool                   `protobuf:"varint,4,opt,name=is_file,json=isFile,proto3" json:"is_file,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestForm) Reset() {
	*x = RequestForm{}
	mi := &file_appointment_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestForm) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestForm) ProtoMessage() {}

func (x *RequestForm) ProtoReflect() protoreflect.Message {
	mi := &file_appointment_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestForm.ProtoReflect.Descriptor instead.
func (*RequestForm) Descriptor() ([]byte, []int) {
	return file_appointment_proto_rawDescGZIP(), []int{3}
}

func (x *RequestForm) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *RequestForm) GetAppointmentId() uint32 {
	if x != nil {
		return x.AppointmentId
	}
	return 0
}

func (x *RequestForm) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *RequestForm) GetIsFile() bool {
	if x != nil {
		return x.IsFile
	}
	return false
}

type ModifyProcedure struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OldVersion    *Appointment           `protobuf:"bytes,1,opt,name=old_version,json=oldVersion,proto3" json:"old_version,omitempty"`
	NewVersion    *Appointment           `protobuf:"bytes,2,opt,name=new_version,json=newVersion,proto3" json:"new_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ModifyProcedure) Reset() {
	*x = ModifyProcedure{}
	mi := &file_appointment_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModifyProcedure) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModifyProcedure) ProtoMessage() {}

func (x *ModifyProcedure) ProtoReflect() protoreflect.Message {
	mi := &file_appointment_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModifyProcedure.ProtoReflect.Descriptor instead.
func (*ModifyProcedure) Descriptor() ([]byte, []int) {
	return file_appointment_proto_rawDescGZIP(), []int{4}
}

func (x *ModifyProcedure) GetOldVersion() *Appointment {
	if x != nil {
		return x.OldVersion
	}
	return nil
}

func (x *ModifyProcedure) GetNewVersion() *Appointment {
	if x != nil {
		return x.NewVersion
	}
	return nil
}

type ReportDeliveryStatus struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ReportId       uint32                 `protobuf:"varint,1,opt,name=report_id,json=reportId,proto3" json:"report_id,omitempty"`
	AppointmentId  uint32                 `protobuf:"varint,2,opt,name=appointment_id,json=appointmentId,proto3" json:"appointment_id,omitempty"`
	DeliveryMethod string                 `protobuf:"bytes,3,opt,name=delivery_method,json=deliveryMethod,proto3" json:"delivery_method,omitempty"`
	Status         string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"` // "sent", "failed"
	Message        string                 `protobuf:"bytes,5,opt,name=message,proto3" json:"message,omitempty"`
	Recipient      string                 `protobuf:"bytes,6,opt,name=recipient,proto3" json:"recipient,omitempty"`
	Timestamp      *timestamp.Timestamp   `protobuf:"bytes,7,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ReportDeliveryStatus) Reset() {
	*x = ReportDeliveryStatus{}
	mi := &file_appointment_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportDeliveryStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportDeliveryStatus) ProtoMessage() {}

func (x *ReportDeliveryStatus) ProtoReflect() protoreflect.Message {
	mi := &file_appointment_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportDeliveryStatus.ProtoReflect.Descriptor instead.
func (*ReportDeliveryStatus) Descriptor() ([]byte, []int) {
	return file_appointment_proto_rawDescGZIP(), []int{5}
}

func (x *ReportDeliveryStatus) GetReportId() uint32 {
	if x != nil {
		return x.ReportId
	}
	return 0
}

func (x *ReportDeliveryStatus) GetAppointmentId() uint32 {
	if x != nil {
		return x.AppointmentId
	}
	return 0
}

func (x *ReportDeliveryStatus) GetDeliveryMethod() string {
	if x != nil {
		return x.DeliveryMethod
	}
	return ""
}

func (x *ReportDeliveryStatus) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ReportDeliveryStatus) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ReportDeliveryStatus) GetRecipient() string {
	if x != nil {
		return x.Recipient
	}
	return ""
}

func (x *ReportDeliveryStatus) GetTimestamp() *timestamp.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

type AppointmentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AppointmentRequest) Reset() {
	*x = AppointmentRequest{}
	mi := &file_appointment_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppointmentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppointmentRequest) ProtoMessage() {}

func (x *AppointmentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_appointment_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppointmentRequest.ProtoReflect.Descriptor instead.
func (*AppointmentRequest) Descriptor() ([]byte, []int) {
	return file_appointment_proto_rawDescGZIP(), []int{6}
}

func (x *AppointmentRequest) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetRecipientCountRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	RecipientType  string                 `protobuf:"bytes,1,opt,name=recipient_type,json=recipientType,proto3" json:"recipient_type,omitempty"` // "patient" or "referring_doctor"
	TargetType     string                 `protobuf:"bytes,2,opt,name=target_type,json=targetType,proto3" json:"target_type,omitempty"`          // "all", "filtered", "specific"
	FilterCriteria *FilterCriteria        `protobuf:"bytes,3,opt,name=filter_criteria,json=filterCriteria,proto3" json:"filter_criteria,omitempty"`
	SpecificIds    []uint32               `protobuf:"varint,4,rep,packed,name=specific_ids,json=specificIds,proto3" json:"specific_ids,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetRecipientCountRequest) Reset() {
	*x = GetRecipientCountRequest{}
	mi := &file_appointment_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRecipientCountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRecipientCountRequest) ProtoMessage() {}

func (x *GetRecipientCountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_appointment_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRecipientCountRequest.ProtoReflect.Descriptor instead.
func (*GetRecipientCountRequest) Descriptor() ([]byte, []int) {
	return file_appointment_proto_rawDescGZIP(), []int{7}
}

func (x *GetRecipientCountRequest) GetRecipientType() string {
	if x != nil {
		return x.RecipientType
	}
	return ""
}

func (x *GetRecipientCountRequest) GetTargetType() string {
	if x != nil {
		return x.TargetType
	}
	return ""
}

func (x *GetRecipientCountRequest) GetFilterCriteria() *FilterCriteria {
	if x != nil {
		return x.FilterCriteria
	}
	return nil
}

func (x *GetRecipientCountRequest) GetSpecificIds() []uint32 {
	if x != nil {
		return x.SpecificIds
	}
	return nil
}

type RecipientCountResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Total         int32                  `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	Breakdown     *RecipientBreakdown    `protobuf:"bytes,2,opt,name=breakdown,proto3" json:"breakdown,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecipientCountResponse) Reset() {
	*x = RecipientCountResponse{}
	mi := &file_appointment_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecipientCountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecipientCountResponse) ProtoMessage() {}

func (x *RecipientCountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_appointment_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecipientCountResponse.ProtoReflect.Descriptor instead.
func (*RecipientCountResponse) Descriptor() ([]byte, []int) {
	return file_appointment_proto_rawDescGZIP(), []int{8}
}

func (x *RecipientCountResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *RecipientCountResponse) GetBreakdown() *RecipientBreakdown {
	if x != nil {
		return x.Breakdown
	}
	return nil
}

type RecipientBreakdown struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WithEmail     int32                  `protobuf:"varint,1,opt,name=with_email,json=withEmail,proto3" json:"with_email,omitempty"`
	WithPhone     int32                  `protobuf:"varint,2,opt,name=with_phone,json=withPhone,proto3" json:"with_phone,omitempty"`
	WithPush      int32                  `protobuf:"varint,3,opt,name=with_push,json=withPush,proto3" json:"with_push,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecipientBreakdown) Reset() {
	*x = RecipientBreakdown{}
	mi := &file_appointment_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecipientBreakdown) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecipientBreakdown) ProtoMessage() {}

func (x *RecipientBreakdown) ProtoReflect() protoreflect.Message {
	mi := &file_appointment_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecipientBreakdown.ProtoReflect.Descriptor instead.
func (*RecipientBreakdown) Descriptor() ([]byte, []int) {
	return file_appointment_proto_rawDescGZIP(), []int{9}
}

func (x *RecipientBreakdown) GetWithEmail() int32 {
	if x != nil {
		return x.WithEmail
	}
	return 0
}

func (x *RecipientBreakdown) GetWithPhone() int32 {
	if x != nil {
		return x.WithPhone
	}
	return 0
}

func (x *RecipientBreakdown) GetWithPush() int32 {
	if x != nil {
		return x.WithPush
	}
	return 0
}

type GetRecipientsRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	RecipientType  string                 `protobuf:"bytes,1,opt,name=recipient_type,json=recipientType,proto3" json:"recipient_type,omitempty"`
	TargetType     string                 `protobuf:"bytes,2,opt,name=target_type,json=targetType,proto3" json:"target_type,omitempty"`
	FilterCriteria *FilterCriteria        `protobuf:"bytes,3,opt,name=filter_criteria,json=filterCriteria,proto3" json:"filter_criteria,omitempty"`
	SpecificIds    []uint32               `protobuf:"varint,4,rep,packed,name=specific_ids,json=specificIds,proto3" json:"specific_ids,omitempty"`
	Offset         int32                  `protobuf:"varint,5,opt,name=offset,proto3" json:"offset,omitempty"`
	Limit          int32                  `protobuf:"varint,6,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetRecipientsRequest) Reset() {
	*x = GetRecipientsRequest{}
	mi := &file_appointment_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRecipientsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRecipientsRequest) ProtoMessage() {}

func (x *GetRecipientsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_appointment_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRecipientsRequest.ProtoReflect.Descriptor instead.
func (*GetRecipientsRequest) Descriptor() ([]byte, []int) {
	return file_appointment_proto_rawDescGZIP(), []int{10}
}

func (x *GetRecipientsRequest) GetRecipientType() string {
	if x != nil {
		return x.RecipientType
	}
	return ""
}

func (x *GetRecipientsRequest) GetTargetType() string {
	if x != nil {
		return x.TargetType
	}
	return ""
}

func (x *GetRecipientsRequest) GetFilterCriteria() *FilterCriteria {
	if x != nil {
		return x.FilterCriteria
	}
	return nil
}

func (x *GetRecipientsRequest) GetSpecificIds() []uint32 {
	if x != nil {
		return x.SpecificIds
	}
	return nil
}

func (x *GetRecipientsRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *GetRecipientsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type RecipientsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Recipients    []*Recipient           `protobuf:"bytes,1,rep,name=recipients,proto3" json:"recipients,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecipientsResponse) Reset() {
	*x = RecipientsResponse{}
	mi := &file_appointment_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecipientsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecipientsResponse) ProtoMessage() {}

func (x *RecipientsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_appointment_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecipientsResponse.ProtoReflect.Descriptor instead.
func (*RecipientsResponse) Descriptor() ([]byte, []int) {
	return file_appointment_proto_rawDescGZIP(), []int{11}
}

func (x *RecipientsResponse) GetRecipients() []*Recipient {
	if x != nil {
		return x.Recipients
	}
	return nil
}

type Recipient struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	PhoneNumber   string                 `protobuf:"bytes,3,opt,name=phone_number,json=phoneNumber,proto3" json:"phone_number,omitempty"`
	DeviceId      string                 `protobuf:"bytes,4,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	FirstName     string                 `protobuf:"bytes,5,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName      string                 `protobuf:"bytes,6,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	RecipientType string                 `protobuf:"bytes,7,opt,name=recipient_type,json=recipientType,proto3" json:"recipient_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Recipient) Reset() {
	*x = Recipient{}
	mi := &file_appointment_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Recipient) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Recipient) ProtoMessage() {}

func (x *Recipient) ProtoReflect() protoreflect.Message {
	mi := &file_appointment_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Recipient.ProtoReflect.Descriptor instead.
func (*Recipient) Descriptor() ([]byte, []int) {
	return file_appointment_proto_rawDescGZIP(), []int{12}
}

func (x *Recipient) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Recipient) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *Recipient) GetPhoneNumber() string {
	if x != nil {
		return x.PhoneNumber
	}
	return ""
}

func (x *Recipient) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *Recipient) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *Recipient) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

func (x *Recipient) GetRecipientType() string {
	if x != nil {
		return x.RecipientType
	}
	return ""
}

type FilterCriteria struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Patient filters
	Gender           *string `protobuf:"bytes,1,opt,name=gender,proto3,oneof" json:"gender,omitempty"`
	AgeMin           *int32  `protobuf:"varint,2,opt,name=age_min,json=ageMin,proto3,oneof" json:"age_min,omitempty"`
	AgeMax           *int32  `protobuf:"varint,3,opt,name=age_max,json=ageMax,proto3,oneof" json:"age_max,omitempty"`
	CreatedAfter     *string `protobuf:"bytes,4,opt,name=created_after,json=createdAfter,proto3,oneof" json:"created_after,omitempty"`    // ISO timestamp
	CreatedBefore    *string `protobuf:"bytes,5,opt,name=created_before,json=createdBefore,proto3,oneof" json:"created_before,omitempty"` // ISO timestamp
	HasEmail         *bool   `protobuf:"varint,8,opt,name=has_email,json=hasEmail,proto3,oneof" json:"has_email,omitempty"`
	HasPhoneNumber   *bool   `protobuf:"varint,9,opt,name=has_phone_number,json=hasPhoneNumber,proto3,oneof" json:"has_phone_number,omitempty"`
	AllowMobileLogin *bool   `protobuf:"varint,10,opt,name=allow_mobile_login,json=allowMobileLogin,proto3,oneof" json:"allow_mobile_login,omitempty"`
	// Referring Doctor filters
	ReferringCenterIds []uint32 `protobuf:"varint,11,rep,packed,name=referring_center_ids,json=referringCenterIds,proto3" json:"referring_center_ids,omitempty"`
	Profession         *string  `protobuf:"bytes,12,opt,name=profession,proto3,oneof" json:"profession,omitempty"`
	HasAccessRequest   *bool    `protobuf:"varint,13,opt,name=has_access_request,json=hasAccessRequest,proto3,oneof" json:"has_access_request,omitempty"`
	IsDisabled         *bool    `protobuf:"varint,14,opt,name=is_disabled,json=isDisabled,proto3,oneof" json:"is_disabled,omitempty"`
	LastLoginAfter     *string  `protobuf:"bytes,15,opt,name=last_login_after,json=lastLoginAfter,proto3,oneof" json:"last_login_after,omitempty"` // ISO timestamp
	// NEW: Patient targeting filters
	BirthMonth      *int32   `protobuf:"varint,16,opt,name=birth_month,json=birthMonth,proto3,oneof" json:"birth_month,omitempty"`                 // 1-12 for birthday campaigns
	OrganizationIds []uint32 `protobuf:"varint,17,rep,packed,name=organization_ids,json=organizationIds,proto3" json:"organization_ids,omitempty"` // Multi-tenant filtering
	ModalityIds     []uint32 `protobuf:"varint,18,rep,packed,name=modality_ids,json=modalityIds,proto3" json:"modality_ids,omitempty"`             // Target by scan type (MRI, CT, etc.)
	ProcedureIds    []uint32 `protobuf:"varint,19,rep,packed,name=procedure_ids,json=procedureIds,proto3" json:"procedure_ids,omitempty"`          // Target by procedures performed
	// NEW: Referring Doctor engagement filters
	DaysSinceLastReferral *int32 `protobuf:"varint,20,opt,name=days_since_last_referral,json=daysSinceLastReferral,proto3,oneof" json:"days_since_last_referral,omitempty"` // Re-engage inactive doctors
	MinReferrals          *int32 `protobuf:"varint,21,opt,name=min_referrals,json=minReferrals,proto3,oneof" json:"min_referrals,omitempty"`                                // High-volume doctors (>= N)
	MaxReferrals          *int32 `protobuf:"varint,22,opt,name=max_referrals,json=maxReferrals,proto3,oneof" json:"max_referrals,omitempty"`                                // Low-volume doctors (<= N)
	// NEW: Referral trend analysis
	ReferralTrend     *string  `protobuf:"bytes,23,opt,name=referral_trend,json=referralTrend,proto3,oneof" json:"referral_trend,omitempty"`                 // "increasing", "decreasing", "stable"
	TrendPeriodDays   *int32   `protobuf:"varint,24,opt,name=trend_period_days,json=trendPeriodDays,proto3,oneof" json:"trend_period_days,omitempty"`        // Compare last N days vs previous N (default: 30)
	TrendThresholdPct *float64 `protobuf:"fixed64,25,opt,name=trend_threshold_pct,json=trendThresholdPct,proto3,oneof" json:"trend_threshold_pct,omitempty"` // Percentage change threshold (default: 20.0)
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *FilterCriteria) Reset() {
	*x = FilterCriteria{}
	mi := &file_appointment_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FilterCriteria) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FilterCriteria) ProtoMessage() {}

func (x *FilterCriteria) ProtoReflect() protoreflect.Message {
	mi := &file_appointment_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FilterCriteria.ProtoReflect.Descriptor instead.
func (*FilterCriteria) Descriptor() ([]byte, []int) {
	return file_appointment_proto_rawDescGZIP(), []int{13}
}

func (x *FilterCriteria) GetGender() string {
	if x != nil && x.Gender != nil {
		return *x.Gender
	}
	return ""
}

func (x *FilterCriteria) GetAgeMin() int32 {
	if x != nil && x.AgeMin != nil {
		return *x.AgeMin
	}
	return 0
}

func (x *FilterCriteria) GetAgeMax() int32 {
	if x != nil && x.AgeMax != nil {
		return *x.AgeMax
	}
	return 0
}

func (x *FilterCriteria) GetCreatedAfter() string {
	if x != nil && x.CreatedAfter != nil {
		return *x.CreatedAfter
	}
	return ""
}

func (x *FilterCriteria) GetCreatedBefore() string {
	if x != nil && x.CreatedBefore != nil {
		return *x.CreatedBefore
	}
	return ""
}

func (x *FilterCriteria) GetHasEmail() bool {
	if x != nil && x.HasEmail != nil {
		return *x.HasEmail
	}
	return false
}

func (x *FilterCriteria) GetHasPhoneNumber() bool {
	if x != nil && x.HasPhoneNumber != nil {
		return *x.HasPhoneNumber
	}
	return false
}

func (x *FilterCriteria) GetAllowMobileLogin() bool {
	if x != nil && x.AllowMobileLogin != nil {
		return *x.AllowMobileLogin
	}
	return false
}

func (x *FilterCriteria) GetReferringCenterIds() []uint32 {
	if x != nil {
		return x.ReferringCenterIds
	}
	return nil
}

func (x *FilterCriteria) GetProfession() string {
	if x != nil && x.Profession != nil {
		return *x.Profession
	}
	return ""
}

func (x *FilterCriteria) GetHasAccessRequest() bool {
	if x != nil && x.HasAccessRequest != nil {
		return *x.HasAccessRequest
	}
	return false
}

func (x *FilterCriteria) GetIsDisabled() bool {
	if x != nil && x.IsDisabled != nil {
		return *x.IsDisabled
	}
	return false
}

func (x *FilterCriteria) GetLastLoginAfter() string {
	if x != nil && x.LastLoginAfter != nil {
		return *x.LastLoginAfter
	}
	return ""
}

func (x *FilterCriteria) GetBirthMonth() int32 {
	if x != nil && x.BirthMonth != nil {
		return *x.BirthMonth
	}
	return 0
}

func (x *FilterCriteria) GetOrganizationIds() []uint32 {
	if x != nil {
		return x.OrganizationIds
	}
	return nil
}

func (x *FilterCriteria) GetModalityIds() []uint32 {
	if x != nil {
		return x.ModalityIds
	}
	return nil
}

func (x *FilterCriteria) GetProcedureIds() []uint32 {
	if x != nil {
		return x.ProcedureIds
	}
	return nil
}

func (x *FilterCriteria) GetDaysSinceLastReferral() int32 {
	if x != nil && x.DaysSinceLastReferral != nil {
		return *x.DaysSinceLastReferral
	}
	return 0
}

func (x *FilterCriteria) GetMinReferrals() int32 {
	if x != nil && x.MinReferrals != nil {
		return *x.MinReferrals
	}
	return 0
}

func (x *FilterCriteria) GetMaxReferrals() int32 {
	if x != nil && x.MaxReferrals != nil {
		return *x.MaxReferrals
	}
	return 0
}

func (x *FilterCriteria) GetReferralTrend() string {
	if x != nil && x.ReferralTrend != nil {
		return *x.ReferralTrend
	}
	return ""
}

func (x *FilterCriteria) GetTrendPeriodDays() int32 {
	if x != nil && x.TrendPeriodDays != nil {
		return *x.TrendPeriodDays
	}
	return 0
}

func (x *FilterCriteria) GetTrendThresholdPct() float64 {
	if x != nil && x.TrendThresholdPct != nil {
		return *x.TrendThresholdPct
	}
	return 0
}

type GetPatientRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PatientId     uint32                 `protobuf:"varint,1,opt,name=patient_id,json=patientId,proto3" json:"patient_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPatientRequest) Reset() {
	*x = GetPatientRequest{}
	mi := &file_appointment_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPatientRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPatientRequest) ProtoMessage() {}

func (x *GetPatientRequest) ProtoReflect() protoreflect.Message {
	mi := &file_appointment_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPatientRequest.ProtoReflect.Descriptor instead.
func (*GetPatientRequest) Descriptor() ([]byte, []int) {
	return file_appointment_proto_rawDescGZIP(), []int{14}
}

func (x *GetPatientRequest) GetPatientId() uint32 {
	if x != nil {
		return x.PatientId
	}
	return 0
}

type GetReferringDoctorRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DoctorId      uint32                 `protobuf:"varint,1,opt,name=doctor_id,json=doctorId,proto3" json:"doctor_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetReferringDoctorRequest) Reset() {
	*x = GetReferringDoctorRequest{}
	mi := &file_appointment_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetReferringDoctorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetReferringDoctorRequest) ProtoMessage() {}

func (x *GetReferringDoctorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_appointment_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetReferringDoctorRequest.ProtoReflect.Descriptor instead.
func (*GetReferringDoctorRequest) Descriptor() ([]byte, []int) {
	return file_appointment_proto_rawDescGZIP(), []int{15}
}

func (x *GetReferringDoctorRequest) GetDoctorId() uint32 {
	if x != nil {
		return x.DoctorId
	}
	return 0
}

var File_appointment_proto protoreflect.FileDescriptor

const file_appointment_proto_rawDesc = "" +
	"\n" +
	"\x11appointment.proto\x12\x05proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x0ereferral.proto\x1a\rpatient.proto\"\xfa\a\n" +
	"\vAppointment\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x1d\n" +
	"\n" +
	"patient_id\x18\x02 \x01(\rR\tpatientId\x12!\n" +
	"\fis_emergency\x18\x03 \x01(\bR\visEmergency\x12!\n" +
	"\fprocedure_id\x18\x04 \x01(\rR\vprocedureId\x12\x1b\n" +
	"\treport_id\x18\x05 \x01(\rR\breportId\x12.\n" +
	"\x13referring_doctor_id\x18\x06 \x01(\rR\x11referringDoctorId\x12.\n" +
	"\x13reporting_doctor_id\x18\a \x01(\rR\x11reportingDoctorId\x12E\n" +
	"\x10appointment_time\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\x0fappointmentTime\x12'\n" +
	"\x0forganization_id\x18\t \x01(\rR\x0eorganizationId\x12\x1d\n" +
	"\n" +
	"payment_id\x18\n" +
	" \x01(\rR\tpaymentId\x12\x12\n" +
	"\x04note\x18\v \x01(\tR\x04note\x12\x16\n" +
	"\x06status\x18\f \x01(\tR\x06status\x125\n" +
	"\frequest_form\x18\r \x03(\v2\x12.proto.RequestFormR\vrequestForm\x12.\n" +
	"\x13has_paid_commission\x18\x0e \x01(\bR\x11hasPaidCommission\x129\n" +
	"\n" +
	"created_at\x18\x0f \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x126\n" +
	"\x17original_appointment_id\x18\x10 \x01(\rR\x15originalAppointmentId\x122\n" +
	"\x15parent_appointment_id\x18\x11 \x01(\rR\x13parentAppointmentId\x12\x18\n" +
	"\aversion\x18\x12 \x01(\x05R\aversion\x12\x1b\n" +
	"\tis_active\x18\x13 \x01(\bR\bisActive\x12\x1f\n" +
	"\vis_original\x18\x14 \x01(\bR\n" +
	"isOriginal\x12\x1f\n" +
	"\vmodified_by\x18\x16 \x01(\rR\n" +
	"modifiedBy\x12/\n" +
	"\x13modification_reason\x18\x17 \x01(\tR\x12modificationReason\x12;\n" +
	"\vmodified_at\x18\x18 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"modifiedAt\x12\x1b\n" +
	"\tis_locked\x18\x19 \x01(\bR\bisLocked\x12,\n" +
	"\x12reason_for_locking\x18\x1a \x01(\tR\x10reasonForLocking\"\xd9\x02\n" +
	"\rReportVersion\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x1b\n" +
	"\treport_id\x18\x02 \x01(\rR\breportId\x12%\n" +
	"\x0eradiologist_id\x18\x03 \x01(\rR\rradiologistId\x12\x1a\n" +
	"\bfindings\x18\x04 \x01(\tR\bfindings\x12 \n" +
	"\vimpressions\x18\x05 \x01(\tR\vimpressions\x12)\n" +
	"\x10clinical_details\x18\x06 \x01(\tR\x0fclinicalDetails\x12\x10\n" +
	"\x03url\x18\a \x01(\tR\x03url\x12\x16\n" +
	"\x06status\x18\b \x01(\tR\x06status\x12\"\n" +
	"\rno_header_url\x18\t \x01(\tR\vnoHeaderUrl\x12=\n" +
	"\fconfirmed_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\vconfirmedAt\"\xc3\x01\n" +
	"\x06Report\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12%\n" +
	"\x0eappointment_id\x18\x02 \x01(\rR\rappointmentId\x12-\n" +
	"\x12referring_hospital\x18\x03 \x01(\tR\x11referringHospital\x12!\n" +
	"\fis_completed\x18\x04 \x01(\bR\visCompleted\x120\n" +
	"\bversions\x18\x05 \x03(\v2\x14.proto.ReportVersionR\bversions\"o\n" +
	"\vRequestForm\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12%\n" +
	"\x0eappointment_id\x18\x02 \x01(\rR\rappointmentId\x12\x10\n" +
	"\x03url\x18\x03 \x01(\tR\x03url\x12\x17\n" +
	"\ais_file\x18\x04 \x01(\bR\x06isFile\"{\n" +
	"\x0fModifyProcedure\x123\n" +
	"\vold_version\x18\x01 \x01(\v2\x12.proto.AppointmentR\n" +
	"oldVersion\x123\n" +
	"\vnew_version\x18\x02 \x01(\v2\x12.proto.AppointmentR\n" +
	"newVersion\"\x8d\x02\n" +
	"\x14ReportDeliveryStatus\x12\x1b\n" +
	"\treport_id\x18\x01 \x01(\rR\breportId\x12%\n" +
	"\x0eappointment_id\x18\x02 \x01(\rR\rappointmentId\x12'\n" +
	"\x0fdelivery_method\x18\x03 \x01(\tR\x0edeliveryMethod\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x05 \x01(\tR\amessage\x12\x1c\n" +
	"\trecipient\x18\x06 \x01(\tR\trecipient\x128\n" +
	"\ttimestamp\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\"$\n" +
	"\x12AppointmentRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\"\xc5\x01\n" +
	"\x18GetRecipientCountRequest\x12%\n" +
	"\x0erecipient_type\x18\x01 \x01(\tR\rrecipientType\x12\x1f\n" +
	"\vtarget_type\x18\x02 \x01(\tR\n" +
	"targetType\x12>\n" +
	"\x0ffilter_criteria\x18\x03 \x01(\v2\x15.proto.FilterCriteriaR\x0efilterCriteria\x12!\n" +
	"\fspecific_ids\x18\x04 \x03(\rR\vspecificIds\"g\n" +
	"\x16RecipientCountResponse\x12\x14\n" +
	"\x05total\x18\x01 \x01(\x05R\x05total\x127\n" +
	"\tbreakdown\x18\x02 \x01(\v2\x19.proto.RecipientBreakdownR\tbreakdown\"o\n" +
	"\x12RecipientBreakdown\x12\x1d\n" +
	"\n" +
	"with_email\x18\x01 \x01(\x05R\twithEmail\x12\x1d\n" +
	"\n" +
	"with_phone\x18\x02 \x01(\x05R\twithPhone\x12\x1b\n" +
	"\twith_push\x18\x03 \x01(\x05R\bwithPush\"\xef\x01\n" +
	"\x14GetRecipientsRequest\x12%\n" +
	"\x0erecipient_type\x18\x01 \x01(\tR\rrecipientType\x12\x1f\n" +
	"\vtarget_type\x18\x02 \x01(\tR\n" +
	"targetType\x12>\n" +
	"\x0ffilter_criteria\x18\x03 \x01(\v2\x15.proto.FilterCriteriaR\x0efilterCriteria\x12!\n" +
	"\fspecific_ids\x18\x04 \x03(\rR\vspecificIds\x12\x16\n" +
	"\x06offset\x18\x05 \x01(\x05R\x06offset\x12\x14\n" +
	"\x05limit\x18\x06 \x01(\x05R\x05limit\"F\n" +
	"\x12RecipientsResponse\x120\n" +
	"\n" +
	"recipients\x18\x01 \x03(\v2\x10.proto.RecipientR\n" +
	"recipients\"\xd4\x01\n" +
	"\tRecipient\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12!\n" +
	"\fphone_number\x18\x03 \x01(\tR\vphoneNumber\x12\x1b\n" +
	"\tdevice_id\x18\x04 \x01(\tR\bdeviceId\x12\x1d\n" +
	"\n" +
	"first_name\x18\x05 \x01(\tR\tfirstName\x12\x1b\n" +
	"\tlast_name\x18\x06 \x01(\tR\blastName\x12%\n" +
	"\x0erecipient_type\x18\a \x01(\tR\rrecipientType\"\xca\n" +
	"\n" +
	"\x0eFilterCriteria\x12\x1b\n" +
	"\x06gender\x18\x01 \x01(\tH\x00R\x06gender\x88\x01\x01\x12\x1c\n" +
	"\aage_min\x18\x02 \x01(\x05H\x01R\x06ageMin\x88\x01\x01\x12\x1c\n" +
	"\aage_max\x18\x03 \x01(\x05H\x02R\x06ageMax\x88\x01\x01\x12(\n" +
	"\rcreated_after\x18\x04 \x01(\tH\x03R\fcreatedAfter\x88\x01\x01\x12*\n" +
	"\x0ecreated_before\x18\x05 \x01(\tH\x04R\rcreatedBefore\x88\x01\x01\x12 \n" +
	"\thas_email\x18\b \x01(\bH\x05R\bhasEmail\x88\x01\x01\x12-\n" +
	"\x10has_phone_number\x18\t \x01(\bH\x06R\x0ehasPhoneNumber\x88\x01\x01\x121\n" +
	"\x12allow_mobile_login\x18\n" +
	" \x01(\bH\aR\x10allowMobileLogin\x88\x01\x01\x120\n" +
	"\x14referring_center_ids\x18\v \x03(\rR\x12referringCenterIds\x12#\n" +
	"\n" +
	"profession\x18\f \x01(\tH\bR\n" +
	"profession\x88\x01\x01\x121\n" +
	"\x12has_access_request\x18\r \x01(\bH\tR\x10hasAccessRequest\x88\x01\x01\x12$\n" +
	"\vis_disabled\x18\x0e \x01(\bH\n" +
	"R\n" +
	"isDisabled\x88\x01\x01\x12-\n" +
	"\x10last_login_after\x18\x0f \x01(\tH\vR\x0elastLoginAfter\x88\x01\x01\x12$\n" +
	"\vbirth_month\x18\x10 \x01(\x05H\fR\n" +
	"birthMonth\x88\x01\x01\x12)\n" +
	"\x10organization_ids\x18\x11 \x03(\rR\x0forganizationIds\x12!\n" +
	"\fmodality_ids\x18\x12 \x03(\rR\vmodalityIds\x12#\n" +
	"\rprocedure_ids\x18\x13 \x03(\rR\fprocedureIds\x12<\n" +
	"\x18days_since_last_referral\x18\x14 \x01(\x05H\rR\x15daysSinceLastReferral\x88\x01\x01\x12(\n" +
	"\rmin_referrals\x18\x15 \x01(\x05H\x0eR\fminReferrals\x88\x01\x01\x12(\n" +
	"\rmax_referrals\x18\x16 \x01(\x05H\x0fR\fmaxReferrals\x88\x01\x01\x12*\n" +
	"\x0ereferral_trend\x18\x17 \x01(\tH\x10R\rreferralTrend\x88\x01\x01\x12/\n" +
	"\x11trend_period_days\x18\x18 \x01(\x05H\x11R\x0ftrendPeriodDays\x88\x01\x01\x123\n" +
	"\x13trend_threshold_pct\x18\x19 \x01(\x01H\x12R\x11trendThresholdPct\x88\x01\x01B\t\n" +
	"\a_genderB\n" +
	"\n" +
	"\b_age_minB\n" +
	"\n" +
	"\b_age_maxB\x10\n" +
	"\x0e_created_afterB\x11\n" +
	"\x0f_created_beforeB\f\n" +
	"\n" +
	"_has_emailB\x13\n" +
	"\x11_has_phone_numberB\x15\n" +
	"\x13_allow_mobile_loginB\r\n" +
	"\v_professionB\x15\n" +
	"\x13_has_access_requestB\x0e\n" +
	"\f_is_disabledB\x13\n" +
	"\x11_last_login_afterB\x0e\n" +
	"\f_birth_monthB\x1b\n" +
	"\x19_days_since_last_referralB\x10\n" +
	"\x0e_min_referralsB\x10\n" +
	"\x0e_max_referralsB\x11\n" +
	"\x0f_referral_trendB\x14\n" +
	"\x12_trend_period_daysB\x16\n" +
	"\x14_trend_threshold_pctJ\x04\b\x06\x10\aJ\x04\b\a\x10\b\"2\n" +
	"\x11GetPatientRequest\x12\x1d\n" +
	"\n" +
	"patient_id\x18\x01 \x01(\rR\tpatientId\"8\n" +
	"\x19GetReferringDoctorRequest\x12\x1b\n" +
	"\tdoctor_id\x18\x01 \x01(\rR\bdoctorId2\xfd\x02\n" +
	"\x12AppointmentService\x12A\n" +
	"\x0eGetAppointment\x12\x19.proto.AppointmentRequest\x1a\x12.proto.Appointment\"\x00\x12S\n" +
	"\x11GetRecipientCount\x12\x1f.proto.GetRecipientCountRequest\x1a\x1d.proto.RecipientCountResponse\x12G\n" +
	"\rGetRecipients\x12\x1b.proto.GetRecipientsRequest\x1a\x19.proto.RecipientsResponse\x126\n" +
	"\n" +
	"GetPatient\x12\x18.proto.GetPatientRequest\x1a\x0e.proto.Patient\x12N\n" +
	"\x12GetReferringDoctor\x12 .proto.GetReferringDoctorRequest\x1a\x16.proto.ReferringDoctorB\x17Z\x15pkg/proto/appointmentb\x06proto3"

var (
	file_appointment_proto_rawDescOnce sync.Once
	file_appointment_proto_rawDescData []byte
)

func file_appointment_proto_rawDescGZIP() []byte {
	file_appointment_proto_rawDescOnce.Do(func() {
		file_appointment_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_appointment_proto_rawDesc), len(file_appointment_proto_rawDesc)))
	})
	return file_appointment_proto_rawDescData
}

var file_appointment_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_appointment_proto_goTypes = []any{
	(*Appointment)(nil),               // 0: proto.Appointment
	(*ReportVersion)(nil),             // 1: proto.ReportVersion
	(*Report)(nil),                    // 2: proto.Report
	(*RequestForm)(nil),               // 3: proto.RequestForm
	(*ModifyProcedure)(nil),           // 4: proto.ModifyProcedure
	(*ReportDeliveryStatus)(nil),      // 5: proto.ReportDeliveryStatus
	(*AppointmentRequest)(nil),        // 6: proto.AppointmentRequest
	(*GetRecipientCountRequest)(nil),  // 7: proto.GetRecipientCountRequest
	(*RecipientCountResponse)(nil),    // 8: proto.RecipientCountResponse
	(*RecipientBreakdown)(nil),        // 9: proto.RecipientBreakdown
	(*GetRecipientsRequest)(nil),      // 10: proto.GetRecipientsRequest
	(*RecipientsResponse)(nil),        // 11: proto.RecipientsResponse
	(*Recipient)(nil),                 // 12: proto.Recipient
	(*FilterCriteria)(nil),            // 13: proto.FilterCriteria
	(*GetPatientRequest)(nil),         // 14: proto.GetPatientRequest
	(*GetReferringDoctorRequest)(nil), // 15: proto.GetReferringDoctorRequest
	(*timestamp.Timestamp)(nil),       // 16: google.protobuf.Timestamp
	(*patient.Patient)(nil),           // 17: proto.Patient
	(*referral.ReferringDoctor)(nil),  // 18: proto.ReferringDoctor
}
var file_appointment_proto_depIdxs = []int32{
	16, // 0: proto.Appointment.appointment_time:type_name -> google.protobuf.Timestamp
	3,  // 1: proto.Appointment.request_form:type_name -> proto.RequestForm
	16, // 2: proto.Appointment.created_at:type_name -> google.protobuf.Timestamp
	16, // 3: proto.Appointment.modified_at:type_name -> google.protobuf.Timestamp
	16, // 4: proto.ReportVersion.confirmed_at:type_name -> google.protobuf.Timestamp
	1,  // 5: proto.Report.versions:type_name -> proto.ReportVersion
	0,  // 6: proto.ModifyProcedure.old_version:type_name -> proto.Appointment
	0,  // 7: proto.ModifyProcedure.new_version:type_name -> proto.Appointment
	16, // 8: proto.ReportDeliveryStatus.timestamp:type_name -> google.protobuf.Timestamp
	13, // 9: proto.GetRecipientCountRequest.filter_criteria:type_name -> proto.FilterCriteria
	9,  // 10: proto.RecipientCountResponse.breakdown:type_name -> proto.RecipientBreakdown
	13, // 11: proto.GetRecipientsRequest.filter_criteria:type_name -> proto.FilterCriteria
	12, // 12: proto.RecipientsResponse.recipients:type_name -> proto.Recipient
	6,  // 13: proto.AppointmentService.GetAppointment:input_type -> proto.AppointmentRequest
	7,  // 14: proto.AppointmentService.GetRecipientCount:input_type -> proto.GetRecipientCountRequest
	10, // 15: proto.AppointmentService.GetRecipients:input_type -> proto.GetRecipientsRequest
	14, // 16: proto.AppointmentService.GetPatient:input_type -> proto.GetPatientRequest
	15, // 17: proto.AppointmentService.GetReferringDoctor:input_type -> proto.GetReferringDoctorRequest
	0,  // 18: proto.AppointmentService.GetAppointment:output_type -> proto.Appointment
	8,  // 19: proto.AppointmentService.GetRecipientCount:output_type -> proto.RecipientCountResponse
	11, // 20: proto.AppointmentService.GetRecipients:output_type -> proto.RecipientsResponse
	17, // 21: proto.AppointmentService.GetPatient:output_type -> proto.Patient
	18, // 22: proto.AppointmentService.GetReferringDoctor:output_type -> proto.ReferringDoctor
	18, // [18:23] is the sub-list for method output_type
	13, // [13:18] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_appointment_proto_init() }
func file_appointment_proto_init() {
	if File_appointment_proto != nil {
		return
	}
	file_appointment_proto_msgTypes[13].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_appointment_proto_rawDesc), len(file_appointment_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_appointment_proto_goTypes,
		DependencyIndexes: file_appointment_proto_depIdxs,
		MessageInfos:      file_appointment_proto_msgTypes,
	}.Build()
	File_appointment_proto = out.File
	file_appointment_proto_goTypes = nil
	file_appointment_proto_depIdxs = nil
}
